from pathlib import Path
from textwrap import dedent
import json

ROOT = Path(r"D:\APPS\IdeasForgeAI")


def write_file(relative_path, content):
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent(content).strip() + "\n", encoding="utf-8")


write_file("backend/agents/database_persistence_agent.py", r"""
import json
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class DatabasePersistenceAgent(BaseAgent):
    name = "database_persistence_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        template_data = context.get("template_selection_agent", {})
        template_id = template_data.get("template_id", "startup_landing")

        if template_id == "crm_tool":
            files = {
                "data/leads.json": json.dumps(self._default_leads(), indent=2)
            }
            summary = "Generated local JSON persistence for CRM leads."
        else:
            files = {
                "data/items.json": "[]\n"
            }
            summary = "Generated local JSON persistence placeholder."

        return self.success(
            summary=summary,
            data={
                "backend_files": files,
                "persistence_type": "local_json",
            },
        )

    def _default_leads(self):
        return [
            {
                "id": 1,
                "name": "Riya Sharma",
                "company": "Bright Foods",
                "stage": "qualified",
                "value": 120000,
                "next_follow_up": "Today 4:00 PM",
            },
            {
                "id": 2,
                "name": "Amit Roy",
                "company": "Nova Retail",
                "stage": "new",
                "value": 28000,
                "next_follow_up": "Tomorrow",
            },
            {
                "id": 3,
                "name": "Priya Sen",
                "company": "Northstar Agency",
                "stage": "proposal",
                "value": 96000,
                "next_follow_up": "Friday",
            },
            {
                "id": 4,
                "name": "Sanjay Das",
                "company": "Prime Services",
                "stage": "won",
                "value": 63000,
                "next_follow_up": None,
            },
        ]
""")


write_file("backend/agents/backend_code_generator_agent.py", r"""
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class BackendCodeGeneratorAgent(BaseAgent):
    name = "backend_code_generator_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        template_id = template_data.get("template_id", "startup_landing")
        template_name = template_data.get("template_name", "Startup Landing Page")

        return self.success(
            summary=f"Generated backend starter code for {template_name}.",
            data={
                "files": {
                    "main.py": self._main_py(project_name, template_id, template_name),
                    "requirements.txt": self._requirements(),
                    ".env.example": self._env_example(project_name),
                    "README.md": self._readme(project_name, template_name),
                }
            },
        )

    def _requirements(self) -> str:
        return "\n".join(["fastapi", "uvicorn[standard]", "pydantic", "python-dotenv", ""])

    def _env_example(self, project_name: str) -> str:
        return "\n".join([
            f"APP_NAME={project_name}",
            "APP_ENV=development",
            "DATABASE_URL=",
            "JWT_SECRET=",
            "",
        ])

    def _readme(self, project_name: str, template_name: str) -> str:
        return "\n".join([
            f"# {project_name} Backend",
            "",
            f"Generated backend starter for {template_name}.",
            "",
            "Run:",
            ".\\run.ps1",
            "",
            "Data persistence:",
            "data/leads.json",
            "",
        ])

    def _main_py(self, project_name: str, template_id: str, template_name: str) -> str:
        if template_id == "crm_tool":
            return self._crm_backend(project_name, template_name)
        return self._generic_backend(project_name, template_name)

    def _base_lines(self, project_name: str, template_name: str):
        project_title = f"{project_name} Backend"
        description = f"Generated by IdeasForgeAI for {template_name}."

        return [
            "import json",
            "from pathlib import Path",
            "from typing import List, Optional",
            "",
            "from fastapi import FastAPI",
            "from fastapi.middleware.cors import CORSMiddleware",
            "from pydantic import BaseModel",
            "",
            "BASE_DIR = Path(__file__).resolve().parent",
            "DATA_DIR = BASE_DIR / 'data'",
            "DATA_DIR.mkdir(parents=True, exist_ok=True)",
            "",
            "app = FastAPI(",
            f"    title={project_title!r},",
            f"    description={description!r},",
            "    version='0.1.0',",
            ")",
            "",
            "app.add_middleware(",
            "    CORSMiddleware,",
            "    allow_origins=['*'],",
            "    allow_credentials=True,",
            "    allow_methods=['*'],",
            "    allow_headers=['*'],",
            ")",
            "",
            "@app.get('/health')",
            "def health_check():",
            "    return {",
            "        'status': 'ok',",
            f"        'service': {project_title!r},",
            f"        'template': {template_name!r},",
            "        'persistence': 'local_json',",
            "    }",
            "",
        ]

    def _crm_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)

        lines += [
            "class Lead(BaseModel):",
            "    id: int",
            "    name: str",
            "    company: str",
            "    stage: str = 'new'",
            "    value: float = 0",
            "    next_follow_up: Optional[str] = None",
            "",
            "LEADS_FILE = DATA_DIR / 'leads.json'",
            "",
            "DEFAULT_LEADS = [",
            "    {'id': 1, 'name': 'Riya Sharma', 'company': 'Bright Foods', 'stage': 'qualified', 'value': 120000, 'next_follow_up': 'Today 4:00 PM'},",
            "    {'id': 2, 'name': 'Amit Roy', 'company': 'Nova Retail', 'stage': 'new', 'value': 28000, 'next_follow_up': 'Tomorrow'},",
            "    {'id': 3, 'name': 'Priya Sen', 'company': 'Northstar Agency', 'stage': 'proposal', 'value': 96000, 'next_follow_up': 'Friday'},",
            "    {'id': 4, 'name': 'Sanjay Das', 'company': 'Prime Services', 'stage': 'won', 'value': 63000, 'next_follow_up': None},",
            "]",
            "",
            "def lead_to_dict(lead: Lead):",
            "    if hasattr(lead, 'model_dump'):",
            "        return lead.model_dump()",
            "    return lead.dict()",
            "",
            "def load_leads() -> List[Lead]:",
            "    if not LEADS_FILE.exists():",
            "        LEADS_FILE.write_text(json.dumps(DEFAULT_LEADS, indent=2), encoding='utf-8')",
            "    try:",
            "        raw = json.loads(LEADS_FILE.read_text(encoding='utf-8'))",
            "        return [Lead(**item) for item in raw]",
            "    except Exception:",
            "        LEADS_FILE.write_text(json.dumps(DEFAULT_LEADS, indent=2), encoding='utf-8')",
            "        return [Lead(**item) for item in DEFAULT_LEADS]",
            "",
            "def save_leads(leads: List[Lead]) -> None:",
            "    LEADS_FILE.write_text(",
            "        json.dumps([lead_to_dict(lead) for lead in leads], indent=2),",
            "        encoding='utf-8',",
            "    )",
            "",
            "leads: List[Lead] = load_leads()",
            "",
            "@app.get('/api/leads')",
            "def list_leads():",
            "    return {'status': 'success', 'leads': leads}",
            "",
            "@app.post('/api/leads')",
            "def create_lead(lead: Lead):",
            "    existing_ids = [item.id for item in leads]",
            "    if lead.id in existing_ids:",
            "        lead.id = max(existing_ids or [0]) + 1",
            "    leads.append(lead)",
            "    save_leads(leads)",
            "    return {'status': 'success', 'lead': lead}",
            "",
            "@app.get('/api/pipeline')",
            "def get_pipeline():",
            "    stages = {'new': [], 'qualified': [], 'proposal': [], 'won': []}",
            "    for lead in leads:",
            "        stages.setdefault(lead.stage, []).append(lead)",
            "    return {'status': 'success', 'pipeline': stages}",
            "",
            "@app.get('/api/followups')",
            "def get_followups():",
            "    followups = [lead for lead in leads if lead.next_follow_up]",
            "    return {'status': 'success', 'followups': followups}",
            "",
            "@app.get('/api/stats')",
            "def get_stats():",
            "    total_value = sum(lead.value for lead in leads)",
            "    return {",
            "        'status': 'success',",
            "        'stats': {",
            "            'total_leads': len(leads),",
            "            'pipeline_value': total_value,",
            "            'followups_due': len([lead for lead in leads if lead.next_follow_up]),",
            "            'conversion_rate': '31%',",
            "        },",
            "    }",
            "",
        ]

        return "\n".join(lines)

    def _generic_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)

        lines += [
            "class Item(BaseModel):",
            "    id: int",
            "    title: str",
            "    description: str = ''",
            "",
            "ITEMS_FILE = DATA_DIR / 'items.json'",
            "",
            "def load_items() -> List[Item]:",
            "    if not ITEMS_FILE.exists():",
            "        ITEMS_FILE.write_text('[]', encoding='utf-8')",
            "    raw = json.loads(ITEMS_FILE.read_text(encoding='utf-8'))",
            "    return [Item(**item) for item in raw]",
            "",
            "def save_items(items: List[Item]) -> None:",
            "    ITEMS_FILE.write_text(json.dumps([item.model_dump() if hasattr(item, 'model_dump') else item.dict() for item in items], indent=2), encoding='utf-8')",
            "",
            "items: List[Item] = load_items()",
            "",
            "@app.get('/api/items')",
            "def list_items():",
            "    return {'status': 'success', 'items': items}",
            "",
            "@app.post('/api/items')",
            "def create_item(item: Item):",
            "    items.append(item)",
            "    save_items(items)",
            "    return {'status': 'success', 'item': item}",
            "",
        ]

        return "\n".join(lines)
""")


write_file("backend/agents/generated_app_export_agent.py", r"""
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult
from backend.core.project_paths import GENERATED_APPS_DIR


class GeneratedAppExportAgent(BaseAgent):
    name = "generated_app_export_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        html_data = context.get("html_builder_agent", {})
        backend_code_data = context.get("backend_code_generator_agent", {})
        frontend_connector_data = context.get("frontend_api_connector_agent", {})
        runtime_data = context.get("runtime_config_agent", {})
        database_data = context.get("database_persistence_agent", {})
        mobile_data = context.get("mobile_packager_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        project_slug = self._slugify(project_name)

        app_dir = GENERATED_APPS_DIR / project_slug
        frontend_dir = app_dir / "frontend"
        backend_dir = app_dir / "backend"
        mobile_dir = app_dir / "mobile"
        docs_dir = app_dir / "docs"
        assets_dir = app_dir / "assets"

        for folder in [frontend_dir, backend_dir, mobile_dir, docs_dir, assets_dir]:
            folder.mkdir(parents=True, exist_ok=True)

        self._write(frontend_dir / "index.html", html_data.get("starter_html", ""))
        self._write(frontend_dir / "styles.css", html_data.get("starter_css", ""))

        for filename, content in runtime_data.get("frontend_files", {}).items():
            self._write(frontend_dir / filename, content)

        for filename, content in frontend_connector_data.get("files", {}).items():
            self._write(frontend_dir / filename, content)

        for filename, content in backend_code_data.get("files", {}).items():
            self._write(backend_dir / filename, self._normalize(content))

        for filename, content in database_data.get("backend_files", {}).items():
            self._write(backend_dir / filename, content)

        for filename, content in runtime_data.get("backend_files", {}).items():
            self._write(backend_dir / filename, content)

        for filename, content in runtime_data.get("root_files", {}).items():
            self._write(app_dir / filename, content)

        self._write(mobile_dir / "README.md", "# Mobile Plan\n\nGenerated mobile package plan.\n")

        self._write(
            app_dir / "README.md",
            self._readme(project_name, idea_data, template_data, runtime_data, database_data),
        )

        self._write(
            docs_dir / "product-plan.json",
            json.dumps(
                {
                    "project_name": project_name,
                    "project_slug": project_slug,
                    "created_at": datetime.utcnow().isoformat() + "Z",
                    "template": template_data,
                    "runtime": runtime_data,
                    "database_persistence": database_data,
                    "mobile_packaging": mobile_data,
                },
                indent=2,
            ),
        )

        return self.success(
            summary="Generated app folder exported successfully.",
            data={
                "project_name": project_name,
                "project_slug": project_slug,
                "export_path": str(app_dir),
                "frontend_entry": str(frontend_dir / "index.html"),
                "backend_entry": str(backend_dir / "main.py"),
                "start_script": str(app_dir / "start-app.ps1"),
            },
        )

    def _slugify(self, value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "-", value)
        return value.strip("-") or "generated-product"

    def _write(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content or "", encoding="utf-8")

    def _normalize(self, content: str) -> str:
        if not isinstance(content, str):
            return ""
        if "\\n" in content and content.count("\n") < 3:
            return content.replace("\\n", "\n")
        return content

    def _readme(
        self,
        project_name: str,
        idea_data: Dict[str, Any],
        template_data: Dict[str, Any],
        runtime_data: Dict[str, Any],
        database_data: Dict[str, Any],
    ) -> str:
        project_slug = self._slugify(project_name)
        backend_port = runtime_data.get("backend_port", 8300)
        preview_port = runtime_data.get("preview_port", 8100)
        raw_idea = idea_data.get("raw_idea", "")
        template_name = template_data.get("template_name", "Generated Template")
        persistence_type = database_data.get("persistence_type", "local_json")

        return "\n".join([
            f"# {project_name}",
            "",
            "Generated by IdeasForgeAI.",
            "",
            "Template:",
            template_name,
            "",
            "Original idea:",
            raw_idea,
            "",
            "Persistence:",
            persistence_type,
            "",
            "Start generated app:",
            ".\\start-app.ps1",
            "",
            "Backend health:",
            f"http://127.0.0.1:{backend_port}/health",
            "",
            "Frontend preview:",
            f"http://127.0.0.1:{preview_port}/generated-apps/{project_slug}/frontend/index.html",
            "",
            "Data file:",
            "backend/data/leads.json",
            "",
        ])
""")


write_file("backend/agents/orchestrator_agent.py", r"""
from backend.agents.backend_api_agent import BackendAPIAgent
from backend.agents.backend_code_generator_agent import BackendCodeGeneratorAgent
from backend.agents.database_persistence_agent import DatabasePersistenceAgent
from backend.agents.frontend_api_connector_agent import FrontendAPIConnectorAgent
from backend.agents.generated_app_export_agent import GeneratedAppExportAgent
from backend.agents.html_builder_agent import HTMLBuilderAgent
from backend.agents.idea_intake_agent import IdeaIntakeAgent
from backend.agents.mobile_packager_agent import MobilePackagerAgent
from backend.agents.runtime_config_agent import RuntimeConfigAgent
from backend.agents.template_selection_agent import TemplateSelectionAgent
from backend.agents.template_ui_renderer_agent import TemplateUIRendererAgent
from backend.agents.ui_blueprint_agent import UIBlueprintAgent
from backend.core.pipeline import BuilderPipeline


def create_default_builder_pipeline() -> BuilderPipeline:
    return BuilderPipeline(
        agents=[
            IdeaIntakeAgent(),
            TemplateSelectionAgent(),
            UIBlueprintAgent(),
            TemplateUIRendererAgent(),
            HTMLBuilderAgent(),
            BackendAPIAgent(),
            BackendCodeGeneratorAgent(),
            FrontendAPIConnectorAgent(),
            RuntimeConfigAgent(),
            DatabasePersistenceAgent(),
            MobilePackagerAgent(),
            GeneratedAppExportAgent(),
        ]
    )
""")

print("Database Persistence Agent added successfully.")
