Set-Location "D:\APPS\IdeasForgeAI"

function Write-File {
    param (
        [string]$Path,
        [string]$Content
    )

    $fullPath = Join-Path (Get-Location) $Path
    $parent = Split-Path $fullPath -Parent

    if (!(Test-Path $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }

    [System.IO.File]::WriteAllText($fullPath, $Content, [System.Text.UTF8Encoding]::new($false))
}

Write-File "backend\agents\generated_app_export_agent.py" @'
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult
from backend.core.project_paths import GENERATED_APPS_DIR


class GeneratedAppExportAgent(BaseAgent):
    name = "generated_app_export_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        html_data = context.get("html_builder_agent", {})
        api_data = context.get("backend_api_agent", {})
        mobile_data = context.get("mobile_packager_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        project_slug = self._slugify(project_name)

        app_dir = GENERATED_APPS_DIR / project_slug
        frontend_dir = app_dir / "frontend"
        backend_dir = app_dir / "backend"
        mobile_dir = app_dir / "mobile"
        docs_dir = app_dir / "docs"
        assets_dir = app_dir / "assets"

        for folder in [frontend_dir, backend_dir, mobile_dir, docs_dir, assets_dir]:
            folder.mkdir(parents=True, exist_ok=True)

        starter_html = html_data.get("starter_html", self._fallback_html(project_name))
        starter_css = html_data.get("starter_css", self._fallback_css())

        self._write(frontend_dir / "index.html", starter_html)
        self._write(frontend_dir / "styles.css", starter_css)

        self._write(
            app_dir / "README.md",
            self._project_readme(project_name, idea_data, api_data, mobile_data),
        )

        self._write(
            docs_dir / "product-plan.json",
            json.dumps(
                {
                    "project_name": project_name,
                    "project_slug": project_slug,
                    "created_at": datetime.utcnow().isoformat() + "Z",
                    "idea": idea_data,
                    "backend_api": api_data,
                    "mobile_packaging": mobile_data,
                },
                indent=2,
            ),
        )

        self._write(
            backend_dir / "README.md",
            "# Backend Plan\n\nThis folder will contain generated backend APIs in the next version.\n",
        )

        self._write(
            mobile_dir / "README.md",
            "# Mobile Plan\n\nThis folder will contain generated mobile packaging files in the next version.\n",
        )

        return self.success(
            summary="Generated app folder exported successfully.",
            data={
                "project_name": project_name,
                "project_slug": project_slug,
                "export_path": str(app_dir),
                "frontend_entry": str(frontend_dir / "index.html"),
                "docs_plan": str(docs_dir / "product-plan.json"),
            },
        )

    def _slugify(self, value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "-", value)
        value = value.strip("-")
        return value or "generated-product"

    def _write(self, path: Path, content: str) -> None:
        path.write_text(content, encoding="utf-8")

    def _fallback_html(self, project_name: str) -> str:
        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{project_name}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main>
    <h1>{project_name}</h1>
    <p>Generated by IdeasForgeAI.</p>
  </main>
</body>
</html>
"""

    def _fallback_css(self) -> str:
        return """body {
  margin: 0;
  font-family: Arial, sans-serif;
  background: #0f172a;
  color: #ffffff;
}
"""

    def _project_readme(
        self,
        project_name: str,
        idea_data: Dict[str, Any],
        api_data: Dict[str, Any],
        mobile_data: Dict[str, Any],
    ) -> str:
        raw_idea = idea_data.get("raw_idea", "")

        return f"""# {project_name}

This app was generated by IdeasForgeAI.

## Original Idea

{raw_idea}

## Generated Structure

- frontend/
- backend/
- mobile/
- docs/
- assets/

## Current Status

This is a starter generated app export.

The current version includes:

- Starter responsive frontend
- Product plan JSON
- Backend API plan
- Mobile packaging plan

## Next Steps

1. Improve generated UI.
2. Add pixel-matched image-to-HTML builder.
3. Generate backend API files.
4. Generate database schema.
5. Add authentication.
6. Package for mobile.
"""
'@

Write-File "backend\agents\orchestrator_agent.py" @'
from backend.agents.backend_api_agent import BackendAPIAgent
from backend.agents.generated_app_export_agent import GeneratedAppExportAgent
from backend.agents.html_builder_agent import HTMLBuilderAgent
from backend.agents.idea_intake_agent import IdeaIntakeAgent
from backend.agents.mobile_packager_agent import MobilePackagerAgent
from backend.agents.ui_blueprint_agent import UIBlueprintAgent
from backend.core.pipeline import BuilderPipeline


def create_default_builder_pipeline() -> BuilderPipeline:
    return BuilderPipeline(
        agents=[
            IdeaIntakeAgent(),
            UIBlueprintAgent(),
            HTMLBuilderAgent(),
            BackendAPIAgent(),
            MobilePackagerAgent(),
            GeneratedAppExportAgent(),
        ]
    )
'@

Write-Host ""
Write-Host "Generated App Export Agent added successfully." -ForegroundColor Green
Write-Host ""
Write-Host "Next:"
Write-Host "uvicorn backend.main:app --reload --port 8100"