from pathlib import Path

ROOT = Path(r"D:\APPS\IdeasForgeAI")


def write_file(relative_path, content):
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


write_file("backend/agents/template_ui_renderer_agent.py", '''
from html import escape
from typing import Any, Dict, List

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class TemplateUIRendererAgent(BaseAgent):
    name = "template_ui_renderer_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        ui_data = context.get("ui_blueprint_agent", {})

        project_name = escape(ui_data.get("project_name", "Generated Product"))
        template_id = ui_data.get("template_id", "startup_landing")
        template_name = escape(ui_data.get("template_name", "Startup Landing Page"))
        raw_idea = escape(idea_data.get("raw_idea", ""))
        features = ui_data.get("recommended_features", [])

        if template_id == "crm_tool":
            page_body = self._render_crm(project_name, template_name, raw_idea)
        elif template_id == "ai_chat_tool":
            page_body = self._render_ai_chat(project_name, template_name, raw_idea)
        elif template_id == "ecommerce_tool":
            page_body = self._render_ecommerce(project_name, template_name, raw_idea)
        else:
            page_body = self._render_default(project_name, template_name, raw_idea, features)

        page_css = self._base_css(template_id)

        return self.success(
            summary=f"Rendered {template_name} product screen.",
            data={
                "template_id": template_id,
                "template_name": template_name,
                "page_body": page_body,
                "page_css": page_css,
            },
        )

    def _logo_text(self, project_name: str) -> str:
        parts = [part[0] for part in project_name.split() if part]
        return ("".join(parts)[:2] or "IF").upper()

    def _render_crm(self, project_name: str, template_name: str, raw_idea: str) -> str:
        logo = self._logo_text(project_name)

        return f"""
  <main class="app-shell crm-screen">
    <nav class="topbar">
      <div class="brand">
        <div class="brand-mark">{logo}</div>
        <div>
          <strong>{project_name}</strong>
          <small>{template_name}</small>
        </div>
      </div>
      <div class="nav-actions">
        <button class="ghost-btn">Import Leads</button>
        <button>Add Lead</button>
      </div>
    </nav>

    <section class="crm-hero">
      <div class="hero-copy">
        <p class="eyebrow">Generated by IdeasForgeAI</p>
        <h1>{project_name} sales command center</h1>
        <p>{raw_idea}</p>
      </div>

      <div class="stats-grid">
        <article class="stat-card">
          <span>Total Leads</span>
          <strong>248</strong>
          <small>+18 this week</small>
        </article>
        <article class="stat-card">
          <span>Deals Won</span>
          <strong>42</strong>
          <small>₹8.4L pipeline</small>
        </article>
        <article class="stat-card">
          <span>Follow-ups</span>
          <strong>17</strong>
          <small>Due today</small>
        </article>
        <article class="stat-card">
          <span>Conversion</span>
          <strong>31%</strong>
          <small>Improving</small>
        </article>
      </div>
    </section>

    <section class="crm-layout">
      <div class="pipeline-board">
        <div class="section-title">
          <h2>Sales Pipeline</h2>
          <span>Live CRM board</span>
        </div>

        <div class="pipeline-columns">
          <article class="pipeline-column">
            <h3>New Leads</h3>
            <div class="lead-card">
              <strong>GreenField Traders</strong>
              <span>Website enquiry</span>
              <small>Potential: ₹45,000</small>
            </div>
            <div class="lead-card">
              <strong>Nova Retail</strong>
              <span>Phone lead</span>
              <small>Potential: ₹28,000</small>
            </div>
          </article>

          <article class="pipeline-column">
            <h3>Qualified</h3>
            <div class="lead-card hot">
              <strong>Bright Foods</strong>
              <span>Demo requested</span>
              <small>Potential: ₹1.2L</small>
            </div>
            <div class="lead-card">
              <strong>Urban Supply Co.</strong>
              <span>Needs pricing</span>
              <small>Potential: ₹74,000</small>
            </div>
          </article>

          <article class="pipeline-column">
            <h3>Proposal</h3>
            <div class="lead-card">
              <strong>Northstar Agency</strong>
              <span>Proposal sent</span>
              <small>Potential: ₹96,000</small>
            </div>
          </article>

          <article class="pipeline-column">
            <h3>Won</h3>
            <div class="lead-card won">
              <strong>Prime Services</strong>
              <span>Payment confirmed</span>
              <small>Closed: ₹63,000</small>
            </div>
          </article>
        </div>
      </div>

      <aside class="side-panel">
        <div class="profile-card">
          <p class="eyebrow">Customer Profile</p>
          <h2>Bright Foods</h2>
          <p>High-intent customer interested in automation and monthly reporting.</p>
          <div class="profile-meta">
            <span>Owner: Riya</span>
            <span>Stage: Qualified</span>
            <span>Value: ₹1.2L</span>
          </div>
        </div>

        <div class="reminder-card">
          <h3>Follow-up Reminders</h3>
          <ul>
            <li>Call Bright Foods at 4:00 PM</li>
            <li>Send proposal to Nova Retail</li>
            <li>Update deal status for Northstar</li>
          </ul>
        </div>
      </aside>
    </section>
  </main>
"""

    def _render_ai_chat(self, project_name: str, template_name: str, raw_idea: str) -> str:
        logo = self._logo_text(project_name)

        return f"""
  <main class="chat-shell">
    <aside class="chat-sidebar">
      <div class="brand">
        <div class="brand-mark">{logo}</div>
        <div>
          <strong>{project_name}</strong>
          <small>{template_name}</small>
        </div>
      </div>
      <button>New Chat</button>
      <div class="history-list">
        <span>Idea generation</span>
        <span>Product plan</span>
        <span>Code export</span>
      </div>
    </aside>

    <section class="chat-workspace">
      <div class="chat-header">
        <div>
          <p class="eyebrow">AI Workspace</p>
          <h1>{project_name}</h1>
        </div>
        <span class="status-pill">Online</span>
      </div>

      <div class="chat-window">
        <div class="bubble ai">Tell me your idea and I will create the product plan.</div>
        <div class="bubble user">{raw_idea}</div>
        <div class="bubble ai">I created the UI, backend plan, mobile plan and export folder.</div>
      </div>

      <div class="prompt-box">
        <input placeholder="Write your next instruction..." />
        <button>Send</button>
      </div>
    </section>
  </main>
"""

    def _render_ecommerce(self, project_name: str, template_name: str, raw_idea: str) -> str:
        logo = self._logo_text(project_name)

        return f"""
  <main class="app-shell">
    <nav class="topbar">
      <div class="brand">
        <div class="brand-mark">{logo}</div>
        <div>
          <strong>{project_name}</strong>
          <small>{template_name}</small>
        </div>
      </div>
      <button>Checkout</button>
    </nav>

    <section class="shop-hero">
      <p class="eyebrow">Generated by IdeasForgeAI</p>
      <h1>{project_name} storefront</h1>
      <p>{raw_idea}</p>
    </section>

    <section class="shop-layout">
      <div class="product-grid">
        <article class="product-card"><h3>Premium Product</h3><p>₹1,299</p><button>Add to cart</button></article>
        <article class="product-card"><h3>Starter Pack</h3><p>₹699</p><button>Add to cart</button></article>
        <article class="product-card"><h3>Business Bundle</h3><p>₹2,499</p><button>Add to cart</button></article>
      </div>
      <aside class="cart-card">
        <h2>Cart Summary</h2>
        <p>3 items selected</p>
        <strong>Total: ₹4,497</strong>
        <button>Proceed</button>
      </aside>
    </section>
  </main>
"""

    def _render_default(self, project_name: str, template_name: str, raw_idea: str, features: List[str]) -> str:
        logo = self._logo_text(project_name)
        cards = ""

        for feature in features or ["Product UI", "Backend Plan", "Mobile Package", "Deployment"]:
            cards += f"""
        <article class="feature-card">
          <h3>{escape(str(feature))}</h3>
          <p>Generated module for {template_name}.</p>
        </article>
"""

        return f"""
  <main class="app-shell">
    <nav class="topbar">
      <div class="brand">
        <div class="brand-mark">{logo}</div>
        <div>
          <strong>{project_name}</strong>
          <small>{template_name}</small>
        </div>
      </div>
      <button>Launch App</button>
    </nav>

    <section class="hero">
      <p class="eyebrow">Generated by IdeasForgeAI</p>
      <h1>{project_name}</h1>
      <p>{raw_idea}</p>
      <button>Start Building</button>
    </section>

    <section class="cards">
      {cards}
    </section>
  </main>
"""

    def _base_css(self, template_id: str) -> str:
        accent_map = {
            "crm_tool": "#38bdf8",
            "ai_chat_tool": "#8b5cf6",
            "ecommerce_tool": "#ec4899",
            "startup_landing": "#38bdf8",
        }

        accent = accent_map.get(template_id, "#38bdf8")

        return """
:root {
  --accent: __ACCENT__;
  --bg: #07111f;
  --panel: rgba(255, 255, 255, 0.08);
  --panel-strong: rgba(255, 255, 255, 0.12);
  --text-soft: #cbd5e1;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, sans-serif;
  background:
    radial-gradient(circle at top left, rgba(56, 189, 248, 0.18), transparent 32%),
    radial-gradient(circle at bottom right, rgba(139, 92, 246, 0.18), transparent 30%),
    var(--bg);
  color: #ffffff;
}

.app-shell {
  min-height: 100vh;
  padding: 28px;
}

.topbar {
  max-width: 1180px;
  margin: 0 auto 24px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 18px 22px;
  border-radius: 22px;
  background: var(--panel);
}

.brand {
  display: flex;
  align-items: center;
  gap: 12px;
}

.brand-mark {
  width: 48px;
  height: 48px;
  border-radius: 16px;
  display: grid;
  place-items: center;
  background: linear-gradient(135deg, var(--accent), #8b5cf6);
  font-weight: 900;
}

.brand strong {
  display: block;
}

.brand small,
.topbar span {
  color: #93c5fd;
}

button,
.ghost-btn {
  border: 0;
  border-radius: 999px;
  padding: 13px 18px;
  font-weight: 900;
  cursor: pointer;
}

.ghost-btn {
  background: rgba(255,255,255,0.12);
  color: white;
}

.nav-actions {
  display: flex;
  gap: 10px;
}

.hero,
.crm-hero,
.shop-hero {
  max-width: 1180px;
  margin: 0 auto 22px;
  padding: 42px;
  border-radius: 30px;
  background: var(--panel);
  box-shadow: 0 28px 90px rgba(0,0,0,0.35);
}

.eyebrow {
  color: var(--accent);
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-weight: 900;
}

h1 {
  margin: 12px 0;
  font-size: clamp(42px, 6vw, 78px);
  line-height: 1;
}

.hero p,
.crm-hero p,
.shop-hero p {
  max-width: 760px;
  color: #dbeafe;
  line-height: 1.6;
}

.crm-hero {
  display: grid;
  grid-template-columns: 1fr 0.95fr;
  gap: 24px;
  align-items: center;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 14px;
}

.stat-card,
.feature-card,
.pipeline-column,
.profile-card,
.reminder-card,
.product-card,
.cart-card {
  background: var(--panel);
  border: 1px solid rgba(255,255,255,0.08);
  border-radius: 24px;
}

.stat-card {
  padding: 18px;
}

.stat-card span,
.stat-card small {
  display: block;
  color: var(--text-soft);
}

.stat-card strong {
  display: block;
  margin: 8px 0;
  font-size: 34px;
}

.crm-layout {
  max-width: 1180px;
  margin: 0 auto;
  display: grid;
  grid-template-columns: 1fr 340px;
  gap: 22px;
}

.section-title {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.section-title span {
  color: #93c5fd;
}

.pipeline-columns {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 14px;
}

.pipeline-column {
  padding: 16px;
  min-height: 280px;
}

.lead-card {
  display: grid;
  gap: 6px;
  margin-top: 12px;
  padding: 14px;
  border-radius: 18px;
  background: rgba(3, 7, 18, 0.55);
}

.lead-card span,
.lead-card small {
  color: var(--text-soft);
}

.lead-card.hot {
  border: 1px solid var(--accent);
}

.lead-card.won {
  border: 1px solid #22c55e;
}

.side-panel {
  display: grid;
  gap: 16px;
}

.profile-card,
.reminder-card {
  padding: 22px;
}

.profile-meta {
  display: grid;
  gap: 8px;
  margin-top: 16px;
}

.profile-meta span,
.reminder-card li {
  color: var(--text-soft);
}

.cards {
  max-width: 1180px;
  margin: 22px auto 0;
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
}

.feature-card {
  padding: 22px;
}

.feature-card p {
  color: var(--text-soft);
}

.chat-shell {
  min-height: 100vh;
  display: grid;
  grid-template-columns: 290px 1fr;
  background: #07111f;
}

.chat-sidebar {
  padding: 24px;
  border-right: 1px solid rgba(255,255,255,0.1);
  background: rgba(255,255,255,0.06);
}

.history-list {
  display: grid;
  gap: 10px;
  margin-top: 24px;
}

.history-list span,
.status-pill {
  padding: 12px;
  border-radius: 14px;
  background: rgba(255,255,255,0.08);
}

.chat-workspace {
  padding: 28px;
}

.chat-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.chat-window {
  margin: 24px 0;
  display: grid;
  gap: 14px;
}

.bubble {
  max-width: 720px;
  padding: 16px 18px;
  border-radius: 22px;
  background: var(--panel);
}

.bubble.user {
  justify-self: end;
  background: rgba(56, 189, 248, 0.18);
}

.prompt-box {
  display: flex;
  gap: 12px;
}

.prompt-box input {
  flex: 1;
  border: 0;
  border-radius: 999px;
  padding: 16px;
}

.shop-layout {
  max-width: 1180px;
  margin: 0 auto;
  display: grid;
  grid-template-columns: 1fr 320px;
  gap: 22px;
}

.product-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 18px;
}

.product-card,
.cart-card {
  padding: 22px;
}

@media (max-width: 980px) {
  .crm-hero,
  .crm-layout,
  .pipeline-columns,
  .cards,
  .chat-shell,
  .shop-layout,
  .product-grid {
    grid-template-columns: 1fr;
  }

  .app-shell,
  .chat-workspace,
  .chat-sidebar {
    padding: 16px;
  }

  .nav-actions {
    display: none;
  }
}
""".replace("__ACCENT__", accent)
''')


write_file("backend/agents/html_builder_agent.py", '''
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class HTMLBuilderAgent(BaseAgent):
    name = "html_builder_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        ui_data = context.get("ui_blueprint_agent", {})
        render_data = context.get("template_ui_renderer_agent", {})

        project_name = ui_data.get("project_name", "Generated Product")
        template_id = render_data.get("template_id", ui_data.get("template_id", "startup_landing"))
        template_name = render_data.get("template_name", ui_data.get("template_name", "Startup Landing Page"))
        page_body = render_data.get("page_body", "")
        page_css = render_data.get("page_css", "")

        starter_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{project_name}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
{page_body}
</body>
</html>
"""

        return self.success(
            summary=f"Built HTML/CSS using {template_name} renderer.",
            data={
                "html_entry_file": "index.html",
                "css_entry_file": "styles.css",
                "template_id": template_id,
                "template_name": template_name,
                "starter_html": starter_html,
                "starter_css": page_css,
            },
        )
''')


write_file("backend/agents/orchestrator_agent.py", '''
from backend.agents.backend_api_agent import BackendAPIAgent
from backend.agents.generated_app_export_agent import GeneratedAppExportAgent
from backend.agents.html_builder_agent import HTMLBuilderAgent
from backend.agents.idea_intake_agent import IdeaIntakeAgent
from backend.agents.mobile_packager_agent import MobilePackagerAgent
from backend.agents.template_selection_agent import TemplateSelectionAgent
from backend.agents.template_ui_renderer_agent import TemplateUIRendererAgent
from backend.agents.ui_blueprint_agent import UIBlueprintAgent
from backend.core.pipeline import BuilderPipeline


def create_default_builder_pipeline() -> BuilderPipeline:
    return BuilderPipeline(
        agents=[
            IdeaIntakeAgent(),
            TemplateSelectionAgent(),
            UIBlueprintAgent(),
            TemplateUIRendererAgent(),
            HTMLBuilderAgent(),
            BackendAPIAgent(),
            MobilePackagerAgent(),
            GeneratedAppExportAgent(),
        ]
    )
''')


print("Template UI Renderer added successfully.")