from pathlib import Path

ROOT = Path(r"D:\APPS\IdeasForgeAI")


def write_file(relative_path, content):
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


backend_code_generator = r'''
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class BackendCodeGeneratorAgent(BaseAgent):
    name = "backend_code_generator_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        template_id = template_data.get("template_id", "startup_landing")
        template_name = template_data.get("template_name", "Startup Landing Page")

        return self.success(
            summary=f"Generated backend starter code for {template_name}.",
            data={
                "files": {
                    "main.py": self._main_py(project_name, template_id, template_name),
                    "requirements.txt": self._requirements(),
                    ".env.example": self._env_example(project_name),
                    "README.md": self._readme(project_name, template_name),
                },
                "run_command": "python -m uvicorn main:app --reload --port 8200",
            },
        )

    def _requirements(self) -> str:
        return "\\n".join([
            "fastapi",
            "uvicorn[standard]",
            "pydantic",
            "python-dotenv",
            "",
        ])

    def _env_example(self, project_name: str) -> str:
        return "\\n".join([
            f"APP_NAME={project_name}",
            "APP_ENV=development",
            "DATABASE_URL=",
            "JWT_SECRET=",
            "",
        ])

    def _readme(self, project_name: str, template_name: str) -> str:
        return "\\n".join([
            f"# {project_name} Backend",
            "",
            f"Generated backend starter for {template_name}.",
            "",
            "## Run",
            "",
            "python -m venv .venv",
            ".\\\\.venv\\\\Scripts\\\\activate",
            "pip install -r requirements.txt",
            "python -m uvicorn main:app --reload --port 8200",
            "",
            "## Health",
            "",
            "http://127.0.0.1:8200/health",
            "",
        ])

    def _main_py(self, project_name: str, template_id: str, template_name: str) -> str:
        if template_id == "crm_tool":
            return self._crm_backend(project_name, template_name)

        return self._generic_backend(project_name, template_name)

    def _base_lines(self, project_name: str, template_name: str):
        return [
            "from typing import List, Optional",
            "",
            "from fastapi import FastAPI",
            "from fastapi.middleware.cors import CORSMiddleware",
            "from pydantic import BaseModel",
            "",
            "",
            "app = FastAPI(",
            f'    title="{project_name} Backend",',
            f'    description="Generated by IdeasForgeAI for {template_name}.",',
            '    version="0.1.0",',
            ")",
            "",
            "app.add_middleware(",
            "    CORSMiddleware,",
            '    allow_origins=["*"],',
            "    allow_credentials=True,",
            '    allow_methods=["*"],',
            '    allow_headers=["*"],',
            ")",
            "",
            "",
            '@app.get("/health")',
            "def health_check():",
            "    return {",
            '        "status": "ok",',
            f'        "service": "{project_name} Backend",',
            f'        "template": "{template_name}",',
            "    }",
            "",
        ]

    def _crm_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)

        lines += [
            "",
            "class Lead(BaseModel):",
            "    id: int",
            "    name: str",
            "    company: str",
            '    stage: str = "new"',
            "    value: float = 0",
            "    next_follow_up: Optional[str] = None",
            "",
            "",
            "leads: List[Lead] = [",
            '    Lead(id=1, name="Riya Sharma", company="Bright Foods", stage="qualified", value=120000, next_follow_up="Today 4:00 PM"),',
            '    Lead(id=2, name="Amit Roy", company="Nova Retail", stage="new", value=28000, next_follow_up="Tomorrow"),',
            '    Lead(id=3, name="Priya Sen", company="Northstar Agency", stage="proposal", value=96000, next_follow_up="Friday"),',
            '    Lead(id=4, name="Sanjay Das", company="Prime Services", stage="won", value=63000, next_follow_up=None),',
            "]",
            "",
            "",
            '@app.get("/api/leads")',
            "def list_leads():",
            '    return {"status": "success", "leads": leads}',
            "",
            "",
            '@app.post("/api/leads")',
            "def create_lead(lead: Lead):",
            "    leads.append(lead)",
            '    return {"status": "success", "lead": lead}',
            "",
            "",
            '@app.get("/api/pipeline")',
            "def get_pipeline():",
            '    stages = {"new": [], "qualified": [], "proposal": [], "won": []}',
            "    for lead in leads:",
            "        stages.setdefault(lead.stage, []).append(lead)",
            '    return {"status": "success", "pipeline": stages}',
            "",
            "",
            '@app.get("/api/followups")',
            "def get_followups():",
            "    followups = [lead for lead in leads if lead.next_follow_up]",
            '    return {"status": "success", "followups": followups}',
            "",
            "",
            '@app.get("/api/stats")',
            "def get_stats():",
            "    total_value = sum(lead.value for lead in leads)",
            "    return {",
            '        "status": "success",',
            '        "stats": {',
            '            "total_leads": len(leads),',
            '            "pipeline_value": total_value,',
            '            "followups_due": len([lead for lead in leads if lead.next_follow_up]),',
            '            "conversion_rate": "31%",',
            "        },",
            "    }",
            "",
        ]

        return "\\n".join(lines)

    def _generic_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)

        lines += [
            "",
            "class Item(BaseModel):",
            "    id: int",
            "    title: str",
            '    description: str = ""',
            "",
            "",
            "items: List[Item] = []",
            "",
            "",
            '@app.get("/api/items")',
            "def list_items():",
            '    return {"status": "success", "items": items}',
            "",
            "",
            '@app.post("/api/items")',
            "def create_item(item: Item):",
            "    items.append(item)",
            '    return {"status": "success", "item": item}',
            "",
        ]

        return "\\n".join(lines)
'''


export_agent = r'''
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult
from backend.core.project_paths import GENERATED_APPS_DIR


class GeneratedAppExportAgent(BaseAgent):
    name = "generated_app_export_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        html_data = context.get("html_builder_agent", {})
        backend_code_data = context.get("backend_code_generator_agent", {})
        mobile_data = context.get("mobile_packager_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        project_slug = self._slugify(project_name)

        app_dir = GENERATED_APPS_DIR / project_slug
        frontend_dir = app_dir / "frontend"
        backend_dir = app_dir / "backend"
        mobile_dir = app_dir / "mobile"
        docs_dir = app_dir / "docs"
        assets_dir = app_dir / "assets"

        for folder in [frontend_dir, backend_dir, mobile_dir, docs_dir, assets_dir]:
            folder.mkdir(parents=True, exist_ok=True)

        self._write(frontend_dir / "index.html", html_data.get("starter_html", ""))
        self._write(frontend_dir / "styles.css", html_data.get("starter_css", ""))

        backend_files = backend_code_data.get("files", {})
        for filename, content in backend_files.items():
            self._write(backend_dir / filename, content)

        self._write(
            mobile_dir / "README.md",
            "# Mobile Plan\\n\\nGenerated mobile packaging plan will be added here.\\n",
        )

        self._write(
            app_dir / "README.md",
            self._project_readme(project_name, idea_data, template_data),
        )

        self._write(
            docs_dir / "product-plan.json",
            json.dumps(
                {
                    "project_name": project_name,
                    "project_slug": project_slug,
                    "created_at": datetime.utcnow().isoformat() + "Z",
                    "idea": idea_data,
                    "template": template_data,
                    "backend_code_files": list(backend_files.keys()),
                    "mobile_packaging": mobile_data,
                },
                indent=2,
            ),
        )

        return self.success(
            summary="Generated app folder exported successfully.",
            data={
                "project_name": project_name,
                "project_slug": project_slug,
                "export_path": str(app_dir),
                "frontend_entry": str(frontend_dir / "index.html"),
                "backend_entry": str(backend_dir / "main.py"),
            },
        )

    def _slugify(self, value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "-", value)
        value = value.strip("-")
        return value or "generated-product"

    def _write(self, path: Path, content: str) -> None:
        path.write_text(content or "", encoding="utf-8")

    def _project_readme(self, project_name: str, idea_data: Dict[str, Any], template_data: Dict[str, Any]) -> str:
        raw_idea = idea_data.get("raw_idea", "")
        template_name = template_data.get("template_name", "Generated Template")

        return f"""# {project_name}

Generated by IdeasForgeAI.

## Template

{template_name}

## Original Idea

{raw_idea}

## Structure

- frontend/
- backend/
- mobile/
- docs/
- assets/

## Backend Run

cd backend
python -m venv .venv
.\\.venv\\Scripts\\activate
pip install -r requirements.txt
python -m uvicorn main:app --reload --port 8200
"""
'''


orchestrator = r'''
from backend.agents.backend_api_agent import BackendAPIAgent
from backend.agents.backend_code_generator_agent import BackendCodeGeneratorAgent
from backend.agents.generated_app_export_agent import GeneratedAppExportAgent
from backend.agents.html_builder_agent import HTMLBuilderAgent
from backend.agents.idea_intake_agent import IdeaIntakeAgent
from backend.agents.mobile_packager_agent import MobilePackagerAgent
from backend.agents.template_selection_agent import TemplateSelectionAgent
from backend.agents.template_ui_renderer_agent import TemplateUIRendererAgent
from backend.agents.ui_blueprint_agent import UIBlueprintAgent
from backend.core.pipeline import BuilderPipeline


def create_default_builder_pipeline() -> BuilderPipeline:
    return BuilderPipeline(
        agents=[
            IdeaIntakeAgent(),
            TemplateSelectionAgent(),
            UIBlueprintAgent(),
            TemplateUIRendererAgent(),
            HTMLBuilderAgent(),
            BackendAPIAgent(),
            BackendCodeGeneratorAgent(),
            MobilePackagerAgent(),
            GeneratedAppExportAgent(),
        ]
    )
'''


write_file("backend/agents/backend_code_generator_agent.py", backend_code_generator)
write_file("backend/agents/generated_app_export_agent.py", export_agent)
write_file("backend/agents/orchestrator_agent.py", orchestrator)

print("Backend generator fixed successfully.")
