from pathlib import Path
from textwrap import dedent

ROOT = Path(r"D:\APPS\IdeasForgeAI")


def write_file(relative_path, content):
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent(content).strip() + "\n", encoding="utf-8")


write_file("backend/agents/backend_code_generator_agent.py", r"""
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class BackendCodeGeneratorAgent(BaseAgent):
    name = "backend_code_generator_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        template_id = template_data.get("template_id", "startup_landing")
        template_name = template_data.get("template_name", "Startup Landing Page")

        return self.success(
            summary=f"Generated backend starter code for {template_name}.",
            data={
                "files": {
                    "main.py": self._main_py(project_name, template_id, template_name),
                    "requirements.txt": self._requirements(),
                    ".env.example": self._env_example(project_name),
                    "README.md": self._readme(project_name, template_name),
                }
            },
        )

    def _requirements(self) -> str:
        return "\n".join(["fastapi", "uvicorn[standard]", "pydantic", "python-dotenv", ""])

    def _env_example(self, project_name: str) -> str:
        return "\n".join([
            f"APP_NAME={project_name}",
            "APP_ENV=development",
            "DATABASE_URL=",
            "JWT_SECRET=",
            "",
        ])

    def _readme(self, project_name: str, template_name: str) -> str:
        return "\n".join([
            f"# {project_name} Backend",
            "",
            f"Generated backend starter for {template_name}.",
            "",
            "Run:",
            "python -m uvicorn main:app --host 127.0.0.1 --port 8300",
            "",
        ])

    def _main_py(self, project_name: str, template_id: str, template_name: str) -> str:
        if template_id == "crm_tool":
            return self._crm_backend(project_name, template_name)
        return self._generic_backend(project_name, template_name)

    def _base_lines(self, project_name: str, template_name: str):
        project_title = f"{project_name} Backend"
        description = f"Generated by IdeasForgeAI for {template_name}."
        return [
            "from typing import List, Optional",
            "",
            "from fastapi import FastAPI",
            "from fastapi.middleware.cors import CORSMiddleware",
            "from pydantic import BaseModel",
            "",
            "app = FastAPI(",
            f"    title={project_title!r},",
            f"    description={description!r},",
            "    version='0.1.0',",
            ")",
            "",
            "app.add_middleware(",
            "    CORSMiddleware,",
            "    allow_origins=['*'],",
            "    allow_credentials=True,",
            "    allow_methods=['*'],",
            "    allow_headers=['*'],",
            ")",
            "",
            "@app.get('/health')",
            "def health_check():",
            "    return {",
            "        'status': 'ok',",
            f"        'service': {project_title!r},",
            f"        'template': {template_name!r},",
            "    }",
            "",
        ]

    def _crm_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)
        lines += [
            "class Lead(BaseModel):",
            "    id: int",
            "    name: str",
            "    company: str",
            "    stage: str = 'new'",
            "    value: float = 0",
            "    next_follow_up: Optional[str] = None",
            "",
            "leads: List[Lead] = [",
            "    Lead(id=1, name='Riya Sharma', company='Bright Foods', stage='qualified', value=120000, next_follow_up='Today 4:00 PM'),",
            "    Lead(id=2, name='Amit Roy', company='Nova Retail', stage='new', value=28000, next_follow_up='Tomorrow'),",
            "    Lead(id=3, name='Priya Sen', company='Northstar Agency', stage='proposal', value=96000, next_follow_up='Friday'),",
            "    Lead(id=4, name='Sanjay Das', company='Prime Services', stage='won', value=63000, next_follow_up=None),",
            "]",
            "",
            "@app.get('/api/leads')",
            "def list_leads():",
            "    return {'status': 'success', 'leads': leads}",
            "",
            "@app.post('/api/leads')",
            "def create_lead(lead: Lead):",
            "    leads.append(lead)",
            "    return {'status': 'success', 'lead': lead}",
            "",
            "@app.get('/api/pipeline')",
            "def get_pipeline():",
            "    stages = {'new': [], 'qualified': [], 'proposal': [], 'won': []}",
            "    for lead in leads:",
            "        stages.setdefault(lead.stage, []).append(lead)",
            "    return {'status': 'success', 'pipeline': stages}",
            "",
            "@app.get('/api/followups')",
            "def get_followups():",
            "    followups = [lead for lead in leads if lead.next_follow_up]",
            "    return {'status': 'success', 'followups': followups}",
            "",
            "@app.get('/api/stats')",
            "def get_stats():",
            "    total_value = sum(lead.value for lead in leads)",
            "    return {",
            "        'status': 'success',",
            "        'stats': {",
            "            'total_leads': len(leads),",
            "            'pipeline_value': total_value,",
            "            'followups_due': len([lead for lead in leads if lead.next_follow_up]),",
            "            'conversion_rate': '31%',",
            "        },",
            "    }",
            "",
        ]
        return "\n".join(lines)

    def _generic_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)
        lines += [
            "class Item(BaseModel):",
            "    id: int",
            "    title: str",
            "    description: str = ''",
            "",
            "items: List[Item] = []",
            "",
            "@app.get('/api/items')",
            "def list_items():",
            "    return {'status': 'success', 'items': items}",
            "",
            "@app.post('/api/items')",
            "def create_item(item: Item):",
            "    items.append(item)",
            "    return {'status': 'success', 'item': item}",
            "",
        ]
        return "\n".join(lines)
""")


write_file("backend/agents/runtime_config_agent.py", r"""
import re
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class RuntimeConfigAgent(BaseAgent):
    name = "runtime_config_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        project_slug = self._slugify(project_name)
        template_name = template_data.get("template_name", "Generated Template")

        backend_port = 8300 + (sum(ord(c) for c in project_slug) % 100)
        preview_port = 8100

        return self.success(
            summary="Generated runtime config and startup scripts.",
            data={
                "frontend_files": {
                    "app-config.js": self._app_config(project_name, project_slug, template_name, backend_port),
                },
                "backend_files": {
                    "run.ps1": self._backend_run_script(backend_port),
                },
                "root_files": {
                    "start-app.ps1": self._start_script(project_slug, backend_port, preview_port),
                },
                "backend_port": backend_port,
                "preview_port": preview_port,
            },
        )

    def _slugify(self, value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "-", value)
        return value.strip("-") or "generated-product"

    def _app_config(self, project_name: str, project_slug: str, template_name: str, backend_port: int) -> str:
        return f'''window.GENERATED_APP_CONFIG = {{
  projectName: "{project_name}",
  projectSlug: "{project_slug}",
  templateName: "{template_name}",
  apiBase: "http://127.0.0.1:{backend_port}"
}};
'''

    def _backend_run_script(self, backend_port: int) -> str:
        return f'''$ErrorActionPreference = "Stop"

if (!(Test-Path ".venv")) {{
    python -m venv .venv
}}

.\\.venv\\Scripts\\activate
python -m pip install -r requirements.txt
python -m uvicorn main:app --host 127.0.0.1 --port {backend_port}
'''

    def _start_script(self, project_slug: str, backend_port: int, preview_port: int) -> str:
        return f'''$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Backend = Join-Path $Root "backend"

Start-Process powershell -ArgumentList @(
    "-NoExit",
    "-Command",
    "cd `"$Backend`"; .\\run.ps1"
)

Start-Sleep -Seconds 3

$Url = "http://127.0.0.1:{preview_port}/generated-apps/{project_slug}/frontend/index.html?v=" + (Get-Date -Format "yyyyMMddHHmmss")
Start-Process $Url
'''
""")


write_file("backend/agents/frontend_api_connector_agent.py", r"""
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class FrontendAPIConnectorAgent(BaseAgent):
    name = "frontend_api_connector_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        template_data = context.get("template_selection_agent", {})
        template_id = template_data.get("template_id", "startup_landing")

        if template_id == "crm_tool":
            app_js = self._crm_js()
        else:
            app_js = "console.log('IdeasForgeAI connector loaded.');\n"

        return self.success(
            summary="Generated frontend API connector.",
            data={"files": {"app.js": app_js}},
        )

    def _crm_js(self) -> str:
        return r'''
const API_BASE =
  (window.GENERATED_APP_CONFIG && window.GENERATED_APP_CONFIG.apiBase) ||
  "http://127.0.0.1:8300";

function showBadge(text, ok) {
  let badge = document.getElementById("apiStatusBadge");
  if (!badge) {
    badge = document.createElement("div");
    badge.id = "apiStatusBadge";
    badge.style.position = "fixed";
    badge.style.right = "18px";
    badge.style.bottom = "18px";
    badge.style.zIndex = "9999";
    badge.style.padding = "10px 14px";
    badge.style.borderRadius = "999px";
    badge.style.fontWeight = "900";
    document.body.appendChild(badge);
  }

  badge.textContent = text;
  badge.style.background = ok ? "#22c55e" : "#ef4444";
  badge.style.color = ok ? "#052e16" : "#450a0a";
}

async function loadCRMData() {
  try {
    const res = await fetch(API_BASE + "/api/stats");
    if (!res.ok) throw new Error("Backend not reachable");

    const data = await res.json();
    const stats = data.stats || {};
    const cards = document.querySelectorAll(".stat-card");

    if (cards[0]) {
      cards[0].querySelector("strong").textContent = stats.total_leads;
      cards[0].querySelector("small").textContent = "Live from backend";
    }

    if (cards[1]) {
      cards[1].querySelector("small").textContent = "₹" + stats.pipeline_value + " pipeline";
    }

    if (cards[2]) {
      cards[2].querySelector("strong").textContent = stats.followups_due;
      cards[2].querySelector("small").textContent = "Due from backend";
    }

    if (cards[3]) {
      cards[3].querySelector("strong").textContent = stats.conversion_rate;
      cards[3].querySelector("small").textContent = "Live CRM metric";
    }

    showBadge("Live API connected", true);
  } catch (err) {
    console.error(err);
    showBadge("Backend not connected", false);
  }
}

window.addEventListener("load", loadCRMData);
'''
""")


write_file("backend/agents/html_builder_agent.py", r"""
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class HTMLBuilderAgent(BaseAgent):
    name = "html_builder_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        ui_data = context.get("ui_blueprint_agent", {})
        render_data = context.get("template_ui_renderer_agent", {})

        project_name = ui_data.get("project_name", "Generated Product")
        template_id = render_data.get("template_id", ui_data.get("template_id", "startup_landing"))
        template_name = render_data.get("template_name", ui_data.get("template_name", "Startup Landing Page"))
        page_body = render_data.get("page_body", "")
        page_css = render_data.get("page_css", "")

        starter_html = "\n".join([
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            '  <meta charset="UTF-8" />',
            '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
            f"  <title>{project_name}</title>",
            '  <link rel="stylesheet" href="./styles.css" />',
            "</head>",
            "<body>",
            page_body,
            '  <script src="./app-config.js"></script>',
            '  <script src="./app.js"></script>',
            "</body>",
            "</html>",
            "",
        ])

        return self.success(
            summary=f"Built HTML/CSS using {template_name} renderer.",
            data={
                "html_entry_file": "index.html",
                "css_entry_file": "styles.css",
                "template_id": template_id,
                "template_name": template_name,
                "starter_html": starter_html,
                "starter_css": page_css,
            },
        )
""")


write_file("backend/agents/generated_app_export_agent.py", r"""
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult
from backend.core.project_paths import GENERATED_APPS_DIR


class GeneratedAppExportAgent(BaseAgent):
    name = "generated_app_export_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        html_data = context.get("html_builder_agent", {})
        backend_code_data = context.get("backend_code_generator_agent", {})
        frontend_connector_data = context.get("frontend_api_connector_agent", {})
        runtime_data = context.get("runtime_config_agent", {})
        mobile_data = context.get("mobile_packager_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        project_slug = self._slugify(project_name)

        app_dir = GENERATED_APPS_DIR / project_slug
        frontend_dir = app_dir / "frontend"
        backend_dir = app_dir / "backend"
        mobile_dir = app_dir / "mobile"
        docs_dir = app_dir / "docs"
        assets_dir = app_dir / "assets"

        for folder in [frontend_dir, backend_dir, mobile_dir, docs_dir, assets_dir]:
            folder.mkdir(parents=True, exist_ok=True)

        self._write(frontend_dir / "index.html", html_data.get("starter_html", ""))
        self._write(frontend_dir / "styles.css", html_data.get("starter_css", ""))

        for filename, content in runtime_data.get("frontend_files", {}).items():
            self._write(frontend_dir / filename, content)

        for filename, content in frontend_connector_data.get("files", {}).items():
            self._write(frontend_dir / filename, content)

        for filename, content in backend_code_data.get("files", {}).items():
            self._write(backend_dir / filename, self._normalize(content))

        for filename, content in runtime_data.get("backend_files", {}).items():
            self._write(backend_dir / filename, content)

        for filename, content in runtime_data.get("root_files", {}).items():
            self._write(app_dir / filename, content)

        self._write(mobile_dir / "README.md", "# Mobile Plan\n\nGenerated mobile package plan.\n")

        self._write(
            app_dir / "README.md",
            self._readme(project_name, idea_data, template_data, runtime_data),
        )

        self._write(
            docs_dir / "product-plan.json",
            json.dumps(
                {
                    "project_name": project_name,
                    "project_slug": project_slug,
                    "created_at": datetime.utcnow().isoformat() + "Z",
                    "template": template_data,
                    "runtime": runtime_data,
                    "mobile_packaging": mobile_data,
                },
                indent=2,
            ),
        )

        return self.success(
            summary="Generated app folder exported successfully.",
            data={
                "project_name": project_name,
                "project_slug": project_slug,
                "export_path": str(app_dir),
                "frontend_entry": str(frontend_dir / "index.html"),
                "backend_entry": str(backend_dir / "main.py"),
                "start_script": str(app_dir / "start-app.ps1"),
            },
        )

    def _slugify(self, value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "-", value)
        return value.strip("-") or "generated-product"

    def _write(self, path: Path, content: str) -> None:
        path.write_text(content or "", encoding="utf-8")

    def _normalize(self, content: str) -> str:
        if not isinstance(content, str):
            return ""
        if "\\n" in content and content.count("\n") < 3:
            return content.replace("\\n", "\n")
        return content

    def _readme(self, project_name: str, idea_data: Dict[str, Any], template_data: Dict[str, Any], runtime_data: Dict[str, Any]) -> str:
        project_slug = self._slugify(project_name)
        backend_port = runtime_data.get("backend_port", 8300)
        preview_port = runtime_data.get("preview_port", 8100)
        raw_idea = idea_data.get("raw_idea", "")
        template_name = template_data.get("template_name", "Generated Template")

        return "\n".join([
            f"# {project_name}",
            "",
            "Generated by IdeasForgeAI.",
            "",
            "Template:",
            template_name,
            "",
            "Original idea:",
            raw_idea,
            "",
            "Start generated app:",
            ".\\start-app.ps1",
            "",
            "Backend health:",
            f"http://127.0.0.1:{backend_port}/health",
            "",
            "Frontend preview:",
            f"http://127.0.0.1:{preview_port}/generated-apps/{project_slug}/frontend/index.html",
            "",
        ])
""")


write_file("backend/agents/orchestrator_agent.py", r"""
from backend.agents.backend_api_agent import BackendAPIAgent
from backend.agents.backend_code_generator_agent import BackendCodeGeneratorAgent
from backend.agents.frontend_api_connector_agent import FrontendAPIConnectorAgent
from backend.agents.generated_app_export_agent import GeneratedAppExportAgent
from backend.agents.html_builder_agent import HTMLBuilderAgent
from backend.agents.idea_intake_agent import IdeaIntakeAgent
from backend.agents.mobile_packager_agent import MobilePackagerAgent
from backend.agents.runtime_config_agent import RuntimeConfigAgent
from backend.agents.template_selection_agent import TemplateSelectionAgent
from backend.agents.template_ui_renderer_agent import TemplateUIRendererAgent
from backend.agents.ui_blueprint_agent import UIBlueprintAgent
from backend.core.pipeline import BuilderPipeline


def create_default_builder_pipeline() -> BuilderPipeline:
    return BuilderPipeline(
        agents=[
            IdeaIntakeAgent(),
            TemplateSelectionAgent(),
            UIBlueprintAgent(),
            TemplateUIRendererAgent(),
            HTMLBuilderAgent(),
            BackendAPIAgent(),
            BackendCodeGeneratorAgent(),
            FrontendAPIConnectorAgent(),
            RuntimeConfigAgent(),
            MobilePackagerAgent(),
            GeneratedAppExportAgent(),
        ]
    )
""")

print("Pipeline Runtime Finalizer Patch applied successfully.")