import type { WorkerScreenState, WorkerTask } from "./workerTypes";

const tasks: WorkerTask[] = [
  {
    id: "WF-1042",
    title: "Validate Founder Dashboard responsive shell",
    summary: "Review the dashboard layout at desktop and mobile breakpoints and collect frontend-only evidence.",
    state: "running",
    priority: "high",
    source: "Code",
    workspace: "IdeasForgeAI Terminal",
    approval: "approved",
    approvalNote: "Read-only visual validation was approved for this fixture scenario.",
    progress: 64,
    createdAt: "2026-07-13T06:38:00.000Z",
    updatedAt: "2026-07-13T07:31:00.000Z",
    currentStep: "Comparing responsive shell landmarks",
    nextStep: "Summarize viewport evidence",
    timeline: [
      { id: "plan", label: "Plan prepared", detail: "Defined routes and viewport checks.", state: "completed", time: "12:08" },
      { id: "approval", label: "Boundary approved", detail: "Read-only browser inspection permitted.", state: "completed", time: "12:16" },
      { id: "inspect", label: "Inspecting layouts", detail: "Desktop and mobile landmarks are being compared.", state: "active", time: "13:01" },
      { id: "report", label: "Evidence report", detail: "Pending completion of responsive checks.", state: "pending" },
    ],
    activity: [
      { id: "a1", level: "notice", time: "13:01", message: "Mobile viewport inspection started." },
      { id: "a2", level: "info", time: "12:42", message: "Desktop module rail landmarks recorded." },
    ],
    logs: [
      { id: "l1", level: "info", time: "13:01:12", message: "viewport=390x844 mode=read-only" },
      { id: "l2", level: "info", time: "12:42:09", message: "route=/dashboard landmarks=present" },
    ],
    diagnostics: [
      { id: "d1", severity: "healthy", label: "Scope boundary", detail: "No mutation or execution capability is connected." },
      { id: "d2", severity: "notice", label: "Fixture state", detail: "Progress is representative frontend data." },
    ],
  },
  {
    id: "WF-1041",
    title: "Prepare bounded release evidence",
    summary: "Assemble build, route, and console checks into a reviewable release note without publishing it.",
    state: "awaiting_approval",
    priority: "critical",
    source: "Terminal",
    workspace: "Founder OS Preview",
    approval: "pending",
    approvalNote: "Human confirmation is required before the hypothetical publish step. No approval control is enabled here.",
    progress: 35,
    createdAt: "2026-07-13T05:55:00.000Z",
    updatedAt: "2026-07-13T07:24:00.000Z",
    currentStep: "Waiting at release evidence gate",
    nextStep: "Continue only after explicit approval",
    timeline: [
      { id: "collect", label: "Evidence collected", detail: "Build and route results grouped.", state: "completed", time: "11:54" },
      { id: "review", label: "Review prepared", detail: "Boundary and risk summary attached.", state: "completed", time: "12:38" },
      { id: "gate", label: "Approval gate", detail: "Waiting for a human decision.", state: "active", time: "12:54" },
      { id: "publish", label: "Publish summary", detail: "Not available in this frontend foundation.", state: "pending" },
    ],
    activity: [{ id: "a1", level: "warning", time: "12:54", message: "Task paused at an approval boundary." }],
    logs: [{ id: "l1", level: "notice", time: "12:54:31", message: "approval_state=pending; execution=disabled" }],
    diagnostics: [{ id: "d1", severity: "healthy", label: "Approval guard", detail: "The task cannot advance from this static interface." }],
  },
  {
    id: "WF-1040",
    title: "Review module route coverage",
    summary: "Check the canonical Founder OS aliases represented by the current frontend router.",
    state: "queued",
    priority: "normal",
    source: "Code",
    workspace: "Founder OS Routes",
    approval: "not_required",
    approvalNote: "This fixture represents a read-only route review and does not require approval.",
    progress: 0,
    createdAt: "2026-07-13T05:28:00.000Z",
    updatedAt: "2026-07-13T05:28:00.000Z",
    currentStep: "Waiting in local preview queue",
    nextStep: "Resolve route aliases",
    timeline: [
      { id: "queued", label: "Queued", detail: "Task definition is ready.", state: "active", time: "10:58" },
      { id: "resolve", label: "Resolve aliases", detail: "Awaiting a future executor.", state: "pending" },
      { id: "report", label: "Report coverage", detail: "Awaiting prior step.", state: "pending" },
    ],
    activity: [{ id: "a1", level: "info", time: "10:58", message: "Task added to the local fixture queue." }],
    logs: [{ id: "l1", level: "info", time: "10:58:00", message: "queue_position=3; executor=unavailable" }],
    diagnostics: [{ id: "d1", severity: "notice", label: "Executor unavailable", detail: "Worker execution is intentionally not connected in FO-1C.1." }],
  },
  {
    id: "WF-1039",
    title: "Inspect provider configuration boundary",
    summary: "Document which provider settings would be required by a future worker service.",
    state: "blocked",
    priority: "high",
    source: "Terminal",
    workspace: "Local Configuration",
    approval: "pending",
    approvalNote: "Configuration access requires trusted workspace context that is not available to this preview.",
    progress: 42,
    createdAt: "2026-07-12T14:20:00.000Z",
    updatedAt: "2026-07-13T04:50:00.000Z",
    currentStep: "Blocked by unavailable trusted context",
    nextStep: "Supply approved configuration context",
    timeline: [
      { id: "inventory", label: "Boundary inventory", detail: "Public configuration surfaces recorded.", state: "completed", time: "19:50" },
      { id: "trusted", label: "Trusted context", detail: "Required context is unavailable.", state: "blocked", time: "10:20" },
      { id: "document", label: "Document contract", detail: "Waiting for the blocked step.", state: "pending" },
    ],
    activity: [{ id: "a1", level: "warning", time: "10:20", message: "Inspection stopped before protected configuration access." }],
    logs: [{ id: "l1", level: "warning", time: "10:20:18", message: "boundary=trusted-context; outcome=blocked" }],
    diagnostics: [{ id: "d1", severity: "warning", label: "Trusted context required", detail: "No paths, secrets, or provider values are exposed in this fixture." }],
  },
  {
    id: "WF-1038",
    title: "Verify frontend build artifacts",
    summary: "Confirm the production frontend bundle completes and produces its expected static artifacts.",
    state: "completed",
    priority: "normal",
    source: "Code",
    workspace: "IdeasForgeAI Terminal",
    approval: "not_required",
    approvalNote: "A local build verification does not require an approval gate in this fixture.",
    progress: 100,
    createdAt: "2026-07-12T11:14:00.000Z",
    updatedAt: "2026-07-12T11:21:00.000Z",
    currentStep: "Completed successfully",
    nextStep: "No further step",
    timeline: [
      { id: "compile", label: "TypeScript compiled", detail: "Type checks completed.", state: "completed", time: "16:46" },
      { id: "bundle", label: "Bundle generated", detail: "Static frontend artifacts produced.", state: "completed", time: "16:50" },
      { id: "complete", label: "Verification complete", detail: "Result recorded locally.", state: "completed", time: "16:51" },
    ],
    activity: [{ id: "a1", level: "info", time: "16:51", message: "Frontend build verification completed." }],
    logs: [{ id: "l1", level: "info", time: "16:51:02", message: "build=passed; publish=false" }],
    diagnostics: [{ id: "d1", severity: "healthy", label: "Build result", detail: "The fixture records a successful local-only verification." }],
  },
];

export const workerFixtureState: WorkerScreenState = {
  tasks,
  dataMode: "local_fixture",
  availability: "foundation_ready",
  lastUpdated: "2026-07-13T07:31:00.000Z",
};
