from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List


SectorTestCase = Dict[str, Any]


SECTOR_TEST_CASES: List[SectorTestCase] = [
    {
        "test_id": "agriculture_farmer_dashboard_inr",
        "prompt": "Create a farmer dashboard app with crop health cards, weather cards, mandi price cards, satellite intelligence, farmer profile, farm records, and AI chat button.",
        "expected_sector_id": "agriculture_farmer",
        "expected_theme_family": "agriculture-green-dashboard",
        "expected_currency_code": "INR",
        "required_screens": ["Crop Health", "Weather", "Mandi Prices", "Satellite Intelligence", "Farmer Profile", "Farm Records", "AI Chat", "Admin Dashboard"],
        "forbidden_sector_ids": ["clinic_healthcare"],
        "forbidden_visible_terms": ["doctor queue", "patient diagnosis", "clinic appointment"],
        "required_aliases": ["crop_health", "weather", "mandi_prices", "satellite_intelligence", "farmer_profile", "farm_records", "ai_chat", "admin"],
        "safety_expectations": ["fake certificates", "advisory", "frontend secrets"],
    },
    {
        "test_id": "insurance_broker_policy_claims",
        "prompt": "Create an insurance broker app with policy comparison, quote request, document upload, claim status, renewals, advisor callback, and admin dashboard.",
        "expected_sector_id": "insurance_broker",
        "expected_theme_family": "finance-trust-blue",
        "required_screens": ["Policy Cards", "Quote Builder", "Claim Tracker", "Renewals", "Admin Dashboard"],
        "forbidden_sector_ids": ["mutual_fund_advisor"],
        "forbidden_visible_terms": ["guaranteed coverage approval", "fake insurance policy", "fake claim approval"],
        "required_aliases": ["policy_cards", "quote_builder", "claim_tracker", "renewals", "admin"],
        "safety_expectations": ["fake insurance policies", "fake claim approvals", "frontend secrets"],
    },
    {
        "test_id": "mutual_fund_broker_sip_inr",
        "prompt": "Create a mobile app for a mutual fund broker with SIP calculator, portfolio tracker, KYC upload, risk profile, advisor booking, and admin dashboard.",
        "expected_sector_id": "mutual_fund_advisor",
        "expected_theme_family": "finance-trust-blue-green",
        "expected_currency_code": "INR",
        "required_screens": ["SIP Calculator", "Portfolio Tracker", "KYC Upload", "Risk Profile", "Advisor Booking", "Admin Dashboard"],
        "forbidden_sector_ids": ["insurance_broker"],
        "forbidden_visible_terms": ["guaranteed returns", "promised profit", "fake KYC approval"],
        "required_aliases": ["sip_calculator", "portfolio_tracker", "kyc_upload", "risk_profile", "advisor_booking", "admin"],
        "safety_expectations": ["estimated growth", "guaranteed returns", "fake investment documents"],
    },
    {
        "test_id": "school_teacher_parent_portal",
        "prompt": "Create a school teacher app with attendance, homework, exam marks, notices, parent messages, timetable, and admin dashboard.",
        "expected_sector_id": "school_teacher_parent",
        "expected_theme_family": "education-soft-blue",
        "required_screens": ["Attendance", "Homework", "Parent Notices", "Exam Results", "Admin Dashboard"],
        "forbidden_sector_ids": ["clinic_healthcare", "insurance_broker"],
        "forbidden_visible_terms": ["patient", "premium renewal", "claim status"],
        "required_aliases": ["attendance", "homework", "parent_notices", "exam_results", "admin"],
        "safety_expectations": ["frontend secrets", "illegal advice"],
    },
    {
        "test_id": "private_tutor_intent_alignment",
        "prompt": "create an app for private tutors",
        "expected_sector_id": "school_teacher_parent",
        "expected_theme_family": "education-soft-blue",
        "required_screens": ["Students", "Classes", "Attendance", "Homework", "Fees", "Parent Messages", "Schedule"],
        "forbidden_sector_ids": ["agriculture_farmer"],
        "forbidden_visible_terms": ["Farmer Dashboard", "crop", "mandi", "satellite", "farm records", "farmer recommendations"],
        "required_visible_terms": ["Private Tutor App", "tutor", "student", "class", "homework", "attendance", "fees", "parent", "student records"],
        "required_aliases": ["students", "classes", "attendance", "homework", "fees", "parent_messages", "schedule"],
        "safety_expectations": ["student data", "frontend secrets"],
    },
    {
        "test_id": "clinic_appointment_queue",
        "prompt": "Create a clinic appointment app with doctor profiles, patient records, appointment booking, queue status, and admin schedule dashboard.",
        "expected_sector_id": "clinic_healthcare",
        "expected_theme_family": "healthcare-calm-teal",
        "required_screens": ["Appointments", "Doctor Schedule", "Patients", "Queue Status", "Admin Dashboard"],
        "forbidden_sector_ids": ["agriculture_farmer"],
        "forbidden_visible_terms": ["crop health", "mandi price", "satellite intelligence"],
        "required_aliases": ["appointments", "doctor_schedule", "patients", "queue_status", "admin"],
        "safety_expectations": ["medical decisions", "frontend secrets"],
    },
    {
        "test_id": "car_detailing_usa_usd",
        "prompt": "Create a mobile app for a car detailing business in USA with service packages, doorstep booking, gallery, payment status, and admin dashboard.",
        "expected_sector_id": "car_detailing",
        "expected_theme_family": "premium-automotive-dark",
        "expected_currency_code": "USD",
        "required_screens": ["Service Packages", "Doorstep Booking", "Before-After Gallery", "Payment Status", "Admin Dashboard"],
        "forbidden_sector_ids": ["restaurant_food", "wedding_event_lawn"],
        "forbidden_visible_terms": ["table booking", "haldi theme", "mehendi theme"],
        "required_aliases": ["service_packages", "doorstep_booking", "gallery", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "gym_london_gbp",
        "prompt": "Create a gym app in London with membership plans, trainer profiles, class booking, attendance tracking, and admin dashboard.",
        "expected_sector_id": "gym_fitness",
        "expected_theme_family": "fitness-energy-bold",
        "expected_currency_code": "GBP",
        "required_screens": ["Membership Plans", "Trainer Profiles", "Class Booking", "Attendance Tracking"],
        "forbidden_sector_ids": ["school_teacher_parent"],
        "forbidden_visible_terms": ["homework", "exam marks", "parent messages"],
        "required_aliases": ["membership_plans", "trainers", "class_booking", "attendance"],
        "safety_expectations": ["frontend secrets", "illegal advice"],
    },
    {
        "test_id": "wedding_event_lawn_india_inr",
        "prompt": "Create an event lawn app in India with wedding packages, haldi and mehendi themes, gallery, booking calendar, enquiry form, and admin dashboard.",
        "expected_sector_id": "wedding_event_lawn",
        "expected_theme_family": "wedding-elegant-warm",
        "expected_currency_code": "INR",
        "required_screens": ["Wedding Packages", "Haldi Theme", "Mehendi Theme", "Gallery", "Booking Calendar", "Enquiry Form"],
        "forbidden_sector_ids": ["car_detailing", "restaurant_food"],
        "forbidden_visible_terms": ["car wash", "kitchen queue", "doctor schedule"],
        "required_aliases": ["wedding_packages", "haldi_theme", "mehendi_theme", "gallery", "enquiry", "admin"],
        "safety_expectations": ["frontend secrets", "fake certificates"],
    },
    {
        "test_id": "restaurant_food_ordering",
        "prompt": "Create a restaurant app with menu catalog, food ordering, table booking, kitchen queue, payment status, and admin dashboard.",
        "expected_sector_id": "restaurant_food",
        "expected_theme_family": "restaurant-warm-food",
        "required_screens": ["Menu", "Food Ordering", "Table Booking", "Kitchen Queue", "Admin Dashboard"],
        "forbidden_sector_ids": ["retail_inventory"],
        "forbidden_visible_terms": ["low stock alerts", "student attendance", "policy claim"],
        "required_aliases": ["menu", "order_food", "book_table", "kitchen_queue", "payments"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "retail_inventory_stock",
        "prompt": "Create a retail inventory app with product catalog, stock tracking, low stock alerts, sales records, purchase orders, and admin dashboard.",
        "expected_sector_id": "retail_inventory",
        "expected_theme_family": "retail-inventory-grid",
        "required_screens": ["Product Catalog", "Inventory", "Low Stock", "Sales Records", "Admin Dashboard"],
        "forbidden_sector_ids": ["restaurant_food"],
        "forbidden_visible_terms": ["table booking", "kitchen queue", "doctor schedule"],
        "required_aliases": ["product_catalog", "inventory", "low_stock", "sales_dashboard", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "government_citizen_grievance",
        "prompt": "Create a government citizen grievance app with citizen service requests, officer dashboard, status tracking, department routing, audit trail, and reports.",
        "expected_sector_id": "government_civic",
        "expected_theme_family": "government-civic-clean",
        "required_screens": ["Citizen Services", "Officer Dashboard", "Application Tracker", "Audit Status", "Service Request", "Department Metrics"],
        "forbidden_sector_ids": ["generic_saas"],
        "forbidden_visible_terms": ["fake certificate", "fake government document", "impersonation workflow"],
        "required_aliases": ["citizen_services", "officer_dashboard", "track_status", "audit_status", "submit_request"],
        "safety_expectations": ["fake documents", "impersonation", "unauthorized public-service claims"],
    },
    {
        "test_id": "real_estate_india_inr",
        "prompt": "Create a real estate property broker app in India with property listings, site visit booking, price comparison, document upload, deal status tracker, and admin dashboard.",
        "expected_sector_id": "real_estate",
        "expected_theme_family": "generic-modern-saas",
        "expected_currency_code": "INR",
        "required_screens": ["Listings", "Site Visits", "Document Checklist", "Admin Dashboard"],
        "forbidden_sector_ids": ["generic_saas"],
        "forbidden_visible_terms": ["policy claim", "SIP calculator", "clinic appointment"],
        "required_aliases": ["listings", "site_visits", "admin"],
        "safety_expectations": ["frontend secrets", "fake government documents"],
    },
    {
        "test_id": "travel_agency_booking",
        "prompt": "Create a travel agency app with trip packages, itinerary builder, hotel booking, flight enquiry, visa checklist, booking tracker, and admin dashboard.",
        "expected_sector_id": "travel_agency",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Packages", "Itinerary", "Bookings", "Visa Checklist", "Admin Dashboard"],
        "forbidden_sector_ids": ["hotel_resort"],
        "forbidden_visible_terms": ["fake visa", "guaranteed approval", "fake certificate"],
        "required_aliases": ["packages", "bookings", "admin"],
        "safety_expectations": ["frontend secrets", "fake government documents"],
    },
    {
        "test_id": "salon_beauty_booking",
        "prompt": "Create a salon beauty app with service menu, appointment booking, stylist calendar, package gallery, bridal makeup enquiries, payments, and admin dashboard.",
        "expected_sector_id": "salon_beauty",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Services", "Appointments", "Stylists", "Gallery", "Payments", "Admin Dashboard"],
        "forbidden_sector_ids": ["clinic_healthcare"],
        "forbidden_visible_terms": ["patient records", "doctor schedule", "prescription"],
        "required_aliases": ["services", "appointments", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "accounting_ca_gst_inr",
        "prompt": "Create an accounting CA firm app in India with GST tracker, tax filing checklist, invoices, ledger reconciliation, client dashboard, and admin dashboard.",
        "expected_sector_id": "accounting_ca",
        "expected_theme_family": "finance-trust-blue",
        "expected_currency_code": "INR",
        "required_screens": ["Clients", "GST Tracker", "Tax Filing", "Invoices", "Reconciliation", "Admin Dashboard"],
        "forbidden_sector_ids": ["mutual_fund_advisor", "insurance_broker"],
        "forbidden_visible_terms": ["guaranteed returns", "claim approval", "policy premium"],
        "required_aliases": ["clients", "gst_tracker", "admin"],
        "safety_expectations": ["frontend secrets", "illegal financial advice"],
    },
    {
        "test_id": "logistics_delivery_fleet",
        "prompt": "Create a logistics delivery app with shipment tracker, courier dispatch, driver assignment, route board, proof of delivery, fleet metrics, and admin dashboard.",
        "expected_sector_id": "logistics_delivery",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Shipments", "Drivers", "Routes", "Delivery Proof", "Admin Dashboard"],
        "forbidden_sector_ids": ["travel_agency"],
        "forbidden_visible_terms": ["visa checklist", "hotel booking", "wedding package"],
        "required_aliases": ["shipments", "drivers", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "construction_project_site",
        "prompt": "Create a construction contractor app with site project progress, material tracker, labour attendance, BOQ milestones, milestone billing, and admin dashboard.",
        "expected_sector_id": "construction_project",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Site Progress", "Materials", "Labour", "Milestones", "Admin Dashboard"],
        "forbidden_sector_ids": ["real_estate"],
        "forbidden_visible_terms": ["property listings", "site visit booking", "tenant"],
        "required_aliases": ["site_progress", "materials", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "hotel_resort_rooms",
        "prompt": "Create a hotel resort app with room booking, guest check-in, reservation tracker, front desk dashboard, housekeeping board, payments, and admin dashboard.",
        "expected_sector_id": "hotel_resort",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Rooms", "Reservations", "Guests", "Housekeeping", "Payments", "Admin Dashboard"],
        "forbidden_sector_ids": ["travel_agency"],
        "forbidden_visible_terms": ["visa checklist", "flight enquiry", "trip package"],
        "required_aliases": ["rooms", "reservations", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "ngo_social_donor",
        "prompt": "Create an NGO social impact app with donation campaigns, volunteer scheduling, beneficiary records, donor tracker, field worker updates, and impact reports.",
        "expected_sector_id": "ngo_social",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Campaigns", "Donors", "Beneficiaries", "Volunteers", "Impact Reports"],
        "forbidden_sector_ids": ["government_civic"],
        "forbidden_visible_terms": ["fake certificate", "officer approval", "government document"],
        "required_aliases": ["campaigns", "donors", "admin"],
        "safety_expectations": ["frontend secrets", "fraud workflows"],
    },
    {
        "test_id": "generic_saas_workflow",
        "prompt": "Create a SaaS workflow dashboard with customer tasks, team analytics, approvals, reports, and a clean admin workspace.",
        "expected_sector_id": "generic_saas",
        "expected_theme_family": "generic-modern-saas",
        "required_screens": ["Home Dashboard", "Workflow Board", "Reports and Insights"],
        "forbidden_sector_ids": ["agriculture_farmer", "clinic_healthcare", "mutual_fund_advisor"],
        "forbidden_visible_terms": ["crop health", "patient records", "SIP calculator"],
        "required_aliases": ["dashboard", "workflow", "reports"],
        "safety_expectations": ["frontend secrets", "approval"],
        "expected_clarification_needed": True,
    },
]


def get_sector_test_cases() -> List[SectorTestCase]:
    return deepcopy(SECTOR_TEST_CASES)
