from typing import Dict

from backend.pixel_converter.schemas import (
    PixelConverterContractRequest,
    PixelConverterContractResponse,
    PixelConverterRequestShape,
    PixelConverterResponseShape,
)


class PixelConverterContractEngine:
    def generate_contract(self, request: PixelConverterContractRequest) -> PixelConverterContractResponse:
        project_name = request.project_name or "IdeasForgeAI Product"
        design_system_version = request.design_system_version or "Phase 6 Design System v1.0"

        output_placeholders: Dict[str, object] = {
            "uploaded_asset": {
                "asset_id": "placeholder-only",
                "file_name": None,
                "file_type": None,
                "source_type": request.reference_source or "contract_preview",
                "session_only": True,
                "stored": False,
            },
            "image_analysis_result": {
                "summary": "No image analysis runs in Phase 7B.",
                "regions": [],
                "components": [],
                "text_blocks": [],
                "confidence": "not_available",
            },
            "component_mapping_placeholder": [
                {
                    "source_region": "Header region",
                    "suggested_component": "Header / Top Navigation component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved navigation spacing and hierarchy.",
                    "responsive_behavior": "Desktop top bar, mobile compact bar.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Sidebar region",
                    "suggested_component": "Sidebar Navigation component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved navigation density and active states.",
                    "responsive_behavior": "Collapse on tablet and mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Hero region",
                    "suggested_component": "Hero Section component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved headline scale and content rhythm.",
                    "responsive_behavior": "Stack content on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Card region",
                    "suggested_component": "Content Card / KPI Card component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved card radius, border, and spacing.",
                    "responsive_behavior": "Move from grid to single column on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Button region",
                    "suggested_component": "Primary / Secondary Button component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved action hierarchy and focus states.",
                    "responsive_behavior": "Allow full-width mobile actions where needed.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Form region",
                    "suggested_component": "Form Field Group component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved input, label, and validation rules.",
                    "responsive_behavior": "Use single-column fields on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Table region",
                    "suggested_component": "Data Table component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved data density and readable row spacing.",
                    "responsive_behavior": "Convert to stacked rows on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Chart region",
                    "suggested_component": "Chart Placeholder component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved analytics treatment and color tokens.",
                    "responsive_behavior": "Use responsive chart area.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Image/media region",
                    "suggested_component": "Media Block component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved media aspect ratios.",
                    "responsive_behavior": "Use fluid media sizing.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Modal region",
                    "suggested_component": "Modal / Dialog component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved overlay, elevation, and dismissal rules.",
                    "responsive_behavior": "Use full-screen sheet behavior on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Chat composer region",
                    "suggested_component": "Chat Input / Composer component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved input and action rules.",
                    "responsive_behavior": "Use fixed bottom composer behavior on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Tab region",
                    "suggested_component": "Navigation Tabs component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved tab styling and selected states.",
                    "responsive_behavior": "Allow horizontal scroll on mobile.",
                    "approval_status": "approval_required",
                },
                {
                    "source_region": "Mobile bottom region",
                    "suggested_component": "Bottom Navigation component",
                    "confidence_placeholder": "placeholder_only",
                    "design_system_rule": "Use approved mobile navigation rules.",
                    "responsive_behavior": "Mobile-only bottom navigation.",
                    "approval_status": "approval_required",
                },
            ],
            "design_system_alignment_placeholder": [
                {
                    "alignment_area": "Color token alignment",
                    "expected_design_system_rule": "Use approved color tokens from the frozen Phase 6 Design System.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Typography alignment",
                    "expected_design_system_rule": "Use approved font scale, hierarchy, and readable text sizing.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Spacing scale alignment",
                    "expected_design_system_rule": "Use approved spacing rhythm and layout density.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Component system alignment",
                    "expected_design_system_rule": "Use approved reusable components before any future generation.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Border radius and shadow alignment",
                    "expected_design_system_rule": "Use approved surface radius, borders, and shadow treatment.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "low",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Responsive behavior alignment",
                    "expected_design_system_rule": "Use approved responsive behavior across desktop, tablet, and mobile.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Accessibility alignment",
                    "expected_design_system_rule": "Use approved contrast, focus, sizing, and readable interaction rules.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Brand personality alignment",
                    "expected_design_system_rule": "Use approved brand personality, tone, and visual restraint.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Mobile-first alignment",
                    "expected_design_system_rule": "Use approved mobile-first layout and touch behavior.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "alignment_area": "Approval readiness",
                    "expected_design_system_rule": "Require explicit human approval before frontend generation.",
                    "current_status": "pending_future_analysis",
                    "placeholder_score": "pending",
                    "risk_level": "high",
                    "required_human_review": True,
                },
            ],
            "pixel_match_score": {
                "layout_match": 0,
                "spacing_match": 0,
                "typography_match": 0,
                "color_match": 0,
                "component_match": 0,
                "responsive_behavior": 0,
                "accessibility": 0,
                "design_system_consistency": 0,
                "overall_confidence": 0,
            },
            "pixel_match_score_preview_placeholder": [
                {
                    "score_area": "Layout structure match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future layout analysis and approved Design System.",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "score_area": "Spacing match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future spacing analysis and approved spacing scale.",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "score_area": "Typography match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future typography analysis and approved type scale.",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "score_area": "Color token match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future token analysis and approved palette.",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "score_area": "Component mapping match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future component mapping approval.",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "score_area": "Responsive behavior match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future breakpoint analysis.",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "score_area": "Accessibility match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future contrast and focus review.",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "score_area": "Brand personality match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future brand consistency review.",
                    "risk_level": "medium",
                    "required_human_review": True,
                },
                {
                    "score_area": "Mobile-first match",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Requires future mobile-first review.",
                    "risk_level": "high",
                    "required_human_review": True,
                },
                {
                    "score_area": "Overall pixel-match readiness",
                    "placeholder_score": "pending",
                    "scoring_status": "not_calculated",
                    "score_basis": "Depends on approved Design System and human review.",
                    "risk_level": "high",
                    "required_human_review": True,
                },
            ],
            "conversion_readiness": {
                "ready_for_phase_7_review": True,
                "ready_for_frontend_generation": False,
                "blocking_reasons": [
                    "Real image analysis is not implemented.",
                    "Pixel-Matched Conversion v1.0 is not approved.",
                    "Phase 8 remains locked.",
                ],
            },
        }

        return PixelConverterContractResponse(
            allowed_input_types=[
                "screenshot_upload_future",
                "pasted_image_future",
                "mobile_app_screenshot_future",
                "website_screenshot_future",
                "dashboard_screenshot_future",
                "hand_drawn_sketch_future",
                "wireframe_future",
                "pdf_page_future",
                "figma_export_reference_future",
            ],
            max_future_file_size_mb=15,
            validation_requirements=[
                "Accept metadata only in Phase 7B.",
                "Reject real file processing until Phase 7C or later.",
                "Require file type allowlist before future upload handling.",
                "Require size limit enforcement before future upload handling.",
                "Require malware and secret safety review before future storage.",
                "Require human approval before frontend generation.",
            ],
            request_shape=PixelConverterRequestShape(
                accepted_fields=[
                    "project_name",
                    "reference_source",
                    "design_system_version",
                ],
                future_upload_fields=[
                    "asset_id",
                    "file_name",
                    "file_type",
                    "file_size_bytes",
                    "width",
                    "height",
                    "orientation",
                    "screen_category",
                    "source_type",
                ],
                blocked_in_phase_7b=[
                    "file_binary",
                    "base64_image",
                    "ocr_text",
                    "html_output",
                    "css_output",
                    "react_output",
                    "provider_payload",
                ],
            ),
            response_shape=PixelConverterResponseShape(
                top_level_fields=[
                    "status",
                    "phase",
                    "mode",
                    "flags",
                    "allowed_input_types",
                    "max_future_file_size_mb",
                    "validation_requirements",
                    "request_shape",
                    "response_shape",
                    "output_placeholders",
                    "design_system_enforcement",
                    "approval_gate",
                    "future_phase_handoff",
                    "safety_limits",
                ],
                output_placeholders=[
                    "uploaded_asset",
                    "image_analysis_result",
                    "layout_regions",
                    "detected_components",
                    "component_mapping_placeholder",
                    "design_system_alignment_placeholder",
                    "pixel_match_score_preview_placeholder",
                    "text_blocks",
                    "color_palette",
                    "typography_profile",
                    "spacing_profile",
                    "responsive_plan",
                    "design_system_alignment",
                    "pixel_match_score",
                    "conversion_readiness",
                ],
                locked_status_fields=[
                    "real_image_analysis_enabled",
                    "ocr_enabled",
                    "pixel_reading_enabled",
                    "canvas_analysis_enabled",
                    "component_mapping_is_placeholder",
                    "design_system_alignment_is_placeholder",
                    "pixel_match_scoring_is_placeholder",
                    "frontend_generation_allowed",
                    "phase_8_unlocked",
                    "external_provider_calls_allowed",
                    "approval_required",
                ],
            ),
            output_placeholders=output_placeholders,
            design_system_enforcement={
                "required": True,
                "source": design_system_version,
                "rule": "Future pixel conversion must align with the approved Phase 6 Design System before any generation handoff.",
                "conflict_behavior": "Flag conflicts for human review; do not blindly copy the reference UI.",
            },
            approval_gate={
                "approval_required": True,
                "approval_message": "Approve Pixel-Matched Conversion v1.0 before moving to frontend generation.",
                "project_name": project_name,
                "phase_8_unlocked": False,
            },
            future_phase_handoff={
                "phase_7c": "Upload UI and local metadata handling.",
                "phase_7d": "Layout detection placeholder.",
                "phase_7e": "Component mapping placeholder.",
                "phase_7f": "Design System alignment output.",
                "phase_7g": "Pixel-match score preview.",
                "phase_7h": "Freeze review.",
                "phase_8": "Locked until Phase 7 is frozen and explicitly approved.",
            },
            safety_limits=[
                "No real image analysis.",
                "No OCR.",
                "No file upload processing.",
                "No uploaded file storage.",
                "No external AI or image provider calls.",
                "No HTML, CSS, React, or frontend code generation.",
                "No database writes.",
                "No deployment.",
                "No Phase 8 unlock.",
            ],
        )

