from typing import Any, Dict

from backend.agents import ideasforgeai_product_template_template
from backend.core.base_agent import BaseAgent
from backend.core.models import AgentResult


class BackendCodeGeneratorAgent(BaseAgent):
    name = "backend_code_generator_agent"

    def run(self, context: Dict[str, Any]) -> AgentResult:
        idea_data = context.get("idea_intake_agent", {})
        template_data = context.get("template_selection_agent", {})

        project_name = idea_data.get("project_name", "Generated Product")
        template_id = template_data.get("template_id", "startup_landing")
        template_name = template_data.get("template_name", "Startup Landing Page")

        if template_id == "ideasforgeai_product_template":
            return self.success(
                summary="Generated IdeasForgeAIProduct backend APIs with local JSON persistence.",
                data={
                    "files": {
                        "main.py": ideasforgeai_product_template_template.backend_code(project_name, template_name),
                        "requirements.txt": self._requirements(),
                        ".env.example": ideasforgeai_product_template_template.env_example(project_name),
                        "README.md": self._readme(project_name, template_name),
                        "supabase_schema.sql": ideasforgeai_product_template_template.supabase_schema(),
                    },
                    "docs_files": {
                        "supabase-plan.md": ideasforgeai_product_template_template.supabase_plan(),
                    },
                },
            )

        return self.success(
            summary=f"Generated backend starter code for {template_name}.",
            data={
                "files": {
                    "main.py": self._main_py(project_name, template_id, template_name),
                    "requirements.txt": self._requirements(),
                    ".env.example": self._env_example(project_name),
                    "README.md": self._readme(project_name, template_name),
                }
            },
        )

    def _requirements(self) -> str:
        return "\n".join(["fastapi", "uvicorn[standard]", "pydantic", "python-dotenv", ""])

    def _env_example(self, project_name: str) -> str:
        return "\n".join([
            f"APP_NAME={project_name}",
            "APP_ENV=development",
            "DATABASE_URL=",
            "JWT_SECRET=",
            "",
        ])

    def _readme(self, project_name: str, template_name: str) -> str:
        return "\n".join([
            f"# {project_name} Backend",
            "",
            f"Generated backend starter for {template_name}.",
            "",
            "Run:",
            ".\\run.ps1",
            "",
            "Data persistence:",
            "data/leads.json",
            "",
        ])

    def _main_py(self, project_name: str, template_id: str, template_name: str) -> str:
        if template_id == "crm_tool":
            return self._crm_backend(project_name, template_name)
        return self._generic_backend(project_name, template_name)

    def _base_lines(self, project_name: str, template_name: str):
        project_title = f"{project_name} Backend"
        description = f"Generated by IdeasForgeAI for {template_name}."

        return [
            "import json",
            "from pathlib import Path",
            "from typing import List, Optional",
            "",
            "from fastapi import FastAPI",
            "from fastapi.middleware.cors import CORSMiddleware",
            "from pydantic import BaseModel",
            "",
            "BASE_DIR = Path(__file__).resolve().parent",
            "DATA_DIR = BASE_DIR / 'data'",
            "DATA_DIR.mkdir(parents=True, exist_ok=True)",
            "",
            "app = FastAPI(",
            f"    title={project_title!r},",
            f"    description={description!r},",
            "    version='0.1.0',",
            ")",
            "",
            "app.add_middleware(",
            "    CORSMiddleware,",
            "    allow_origins=['*'],",
            "    allow_credentials=True,",
            "    allow_methods=['*'],",
            "    allow_headers=['*'],",
            ")",
            "",
            "@app.get('/health')",
            "def health_check():",
            "    return {",
            "        'status': 'ok',",
            f"        'service': {project_title!r},",
            f"        'template': {template_name!r},",
            "        'persistence': 'local_json',",
            "    }",
            "",
        ]

    def _crm_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)

        lines += [
            "class Lead(BaseModel):",
            "    id: int",
            "    name: str",
            "    company: str",
            "    stage: str = 'new'",
            "    value: float = 0",
            "    next_follow_up: Optional[str] = None",
            "",
            "LEADS_FILE = DATA_DIR / 'leads.json'",
            "",
            "DEFAULT_LEADS = [",
            "    {'id': 1, 'name': 'Riya Sharma', 'company': 'Bright Foods', 'stage': 'qualified', 'value': 120000, 'next_follow_up': 'Today 4:00 PM'},",
            "    {'id': 2, 'name': 'Amit Roy', 'company': 'Nova Retail', 'stage': 'new', 'value': 28000, 'next_follow_up': 'Tomorrow'},",
            "    {'id': 3, 'name': 'Priya Sen', 'company': 'Northstar Agency', 'stage': 'proposal', 'value': 96000, 'next_follow_up': 'Friday'},",
            "    {'id': 4, 'name': 'Sanjay Das', 'company': 'Prime Services', 'stage': 'won', 'value': 63000, 'next_follow_up': None},",
            "]",
            "",
            "def lead_to_dict(lead: Lead):",
            "    if hasattr(lead, 'model_dump'):",
            "        return lead.model_dump()",
            "    return lead.dict()",
            "",
            "def load_leads() -> List[Lead]:",
            "    if not LEADS_FILE.exists():",
            "        LEADS_FILE.write_text(json.dumps(DEFAULT_LEADS, indent=2), encoding='utf-8')",
            "    try:",
            "        raw = json.loads(LEADS_FILE.read_text(encoding='utf-8'))",
            "        return [Lead(**item) for item in raw]",
            "    except Exception:",
            "        LEADS_FILE.write_text(json.dumps(DEFAULT_LEADS, indent=2), encoding='utf-8')",
            "        return [Lead(**item) for item in DEFAULT_LEADS]",
            "",
            "def save_leads(leads: List[Lead]) -> None:",
            "    LEADS_FILE.write_text(",
            "        json.dumps([lead_to_dict(lead) for lead in leads], indent=2),",
            "        encoding='utf-8',",
            "    )",
            "",
            "leads: List[Lead] = load_leads()",
            "",
            "@app.get('/api/leads')",
            "def list_leads():",
            "    return {'status': 'success', 'leads': leads}",
            "",
            "@app.post('/api/leads')",
            "def create_lead(lead: Lead):",
            "    existing_ids = [item.id for item in leads]",
            "    if lead.id in existing_ids:",
            "        lead.id = max(existing_ids or [0]) + 1",
            "    leads.append(lead)",
            "    save_leads(leads)",
            "    return {'status': 'success', 'lead': lead}",
            "",
            "@app.put('/api/leads/{lead_id}')",
            "def update_lead(lead_id: int, updated_lead: Lead):",
            "    for index, existing in enumerate(leads):",
            "        if existing.id == lead_id:",
            "            updated_lead.id = lead_id",
            "            leads[index] = updated_lead",
            "            save_leads(leads)",
            "            return {'status': 'success', 'lead': updated_lead}",
            "    return {'status': 'error', 'message': 'Lead not found'}",
            "",
            "@app.delete('/api/leads/{lead_id}')",
            "def delete_lead(lead_id: int):",
            "    for index, existing in enumerate(leads):",
            "        if existing.id == lead_id:",
            "            deleted = leads.pop(index)",
            "            save_leads(leads)",
            "            return {'status': 'success', 'deleted': deleted}",
            "    return {'status': 'error', 'message': 'Lead not found'}",
            "",
            "@app.get('/api/pipeline')",
            "def get_pipeline():",
            "    stages = {'new': [], 'qualified': [], 'proposal': [], 'won': []}",
            "    for lead in leads:",
            "        stages.setdefault(lead.stage, []).append(lead)",
            "    return {'status': 'success', 'pipeline': stages}",
            "",
            "@app.get('/api/followups')",
            "def get_followups():",
            "    followups = [lead for lead in leads if lead.next_follow_up]",
            "    return {'status': 'success', 'followups': followups}",
            "",
            "@app.get('/api/stats')",
            "def get_stats():",
            "    total_value = sum(lead.value for lead in leads)",
            "    return {",
            "        'status': 'success',",
            "        'stats': {",
            "            'total_leads': len(leads),",
            "            'pipeline_value': total_value,",
            "            'followups_due': len([lead for lead in leads if lead.next_follow_up]),",
            "            'conversion_rate': '31%',",
            "        },",
            "    }",
            "",
        ]

        return "\n".join(lines)

    def _generic_backend(self, project_name: str, template_name: str) -> str:
        lines = self._base_lines(project_name, template_name)

        lines += [
            "class Item(BaseModel):",
            "    id: int",
            "    title: str",
            "    description: str = ''",
            "",
            "ITEMS_FILE = DATA_DIR / 'items.json'",
            "",
            "def load_items() -> List[Item]:",
            "    if not ITEMS_FILE.exists():",
            "        ITEMS_FILE.write_text('[]', encoding='utf-8')",
            "    raw = json.loads(ITEMS_FILE.read_text(encoding='utf-8'))",
            "    return [Item(**item) for item in raw]",
            "",
            "def save_items(items: List[Item]) -> None:",
            "    ITEMS_FILE.write_text(json.dumps([item.model_dump() if hasattr(item, 'model_dump') else item.dict() for item in items], indent=2), encoding='utf-8')",
            "",
            "items: List[Item] = load_items()",
            "",
            "@app.get('/api/items')",
            "def list_items():",
            "    return {'status': 'success', 'items': items}",
            "",
            "@app.post('/api/items')",
            "def create_item(item: Item):",
            "    items.append(item)",
            "    save_items(items)",
            "    return {'status': 'success', 'item': item}",
            "",
        ]

        return "\n".join(lines)

