from backend.frontend_generator.schemas import (
    FrontendGeneratorContractRequest,
    FrontendGeneratorContractResponse,
    FrontendGeneratorRequestShape,
    FrontendGeneratorResponseShape,
)


class FrontendGeneratorContractEngine:
    def generate_contract(self, request: FrontendGeneratorContractRequest) -> FrontendGeneratorContractResponse:
        project_name = request.project_name or "IdeasForgeAI Product"
        design_system_version = request.design_system_version or "Phase 6 Design System v1.0"

        blocked_fields = [
            "html_output",
            "css_output",
            "react_output",
            "generated_files",
            "generated_app_path",
            "file_write_request",
            "deploy_request",
            "provider_prompt",
            "secret_value",
            "database_write",
            "supabase_config",
            "auth_config",
        ]

        return FrontendGeneratorContractResponse(
            project_name=project_name,
            request_shape=FrontendGeneratorRequestShape(
                accepted_fields=[
                    "project_name",
                    "target_platform",
                    "target_screen_type",
                    "design_system_version",
                    "product_brain_reference",
                    "pixel_converter_reference",
                    "approval_context",
                ],
                blocked_fields=blocked_fields,
                required_product_brain_inputs=[
                    "approved_product_strategy",
                    "approved_requirements",
                    "approved_product_blueprint",
                    "approved_screen_plan",
                    "approval_checkpoint",
                ],
                required_design_system_inputs=[
                    "approved_design_system_version",
                    "design_positioning",
                    "typography_rules",
                    "color_token_rules",
                    "component_rules",
                    "mobile_first_rules",
                    "accessibility_rules",
                ],
                required_pixel_converter_inputs=[
                    "pixel_converter_contract_status",
                    "layout_detection_placeholder",
                    "component_mapping_placeholder",
                    "design_system_alignment_placeholder",
                    "pixel_match_score_preview_placeholder",
                    "human_approval_state",
                ],
            ),
            response_shape=FrontendGeneratorResponseShape(
                top_level_fields=[
                    "status",
                    "phase",
                    "mode",
                    "project_name",
                    "safety_locks",
                    "request_shape",
                    "response_shape",
                    "allowed_safe_input_metadata",
                    "future_screen_targets",
                    "future_output_type_placeholders",
                    "approval_gate",
                    "blocked_outputs",
                    "next_phase_handoff",
                    "safety_limits",
                ],
                preview_ready_placeholders=[
                    "screen_plan_summary",
                    "component_plan_summary",
                    "responsive_strategy_summary",
                    "design_system_dependency_summary",
                    "approval_readiness_summary",
                ],
                blocked_output_fields=blocked_fields,
                locked_status_fields=[
                    "frontend_generation_allowed",
                    "html_generation_allowed",
                    "css_generation_allowed",
                    "react_generation_allowed",
                    "generated_app_write_allowed",
                    "generated_files_allowed",
                    "deployment_allowed",
                    "provider_calls_allowed",
                    "database_writes_allowed",
                    "supabase_allowed",
                    "auth_allowed",
                    "phase_8_generation_unlocked",
                    "approval_required",
                ],
            ),
            allowed_safe_input_metadata={
                "project_name": project_name,
                "target_platform": request.target_platform or "web",
                "target_screen_type": request.target_screen_type or "single_page_preview",
                "design_system_version": design_system_version,
                "product_brain_reference": request.product_brain_reference or "Phase 5 Product Brain approved output",
                "pixel_converter_reference": request.pixel_converter_reference or "Phase 7 Pixel-Matched placeholder output",
                "approval_context": request.approval_context or "approval_required",
            },
            future_screen_targets={
                "single_page_preview": "Future Phase 8C may prepare a static preview plan after approval.",
                "multi_page_app_structure": "Future Phase 8D may prepare a multi-page structure after approval.",
                "responsive_preview": "Future Phase 8E may prepare mobile and desktop variants after approval.",
                "design_system_enforced_preview": "Future Phase 8F may enforce approved Design System rules after approval.",
            },
            future_output_type_placeholders={
                "html_output": "blocked_in_phase_8b",
                "css_output": "blocked_in_phase_8b",
                "react_output": "blocked_in_phase_8b",
                "generated_files": [],
                "generated_app_path": None,
                "preview_artifact": "not_created_in_phase_8b",
            },
            approval_gate={
                "approval_required": True,
                "approval_message": "Approve Safe Frontend Generator Contract v1.0 before moving to Phase 8C Single Page Static Preview Generator.",
                "phase_8_generation_unlocked": False,
                "frontend_generation_allowed": False,
            },
            blocked_outputs={field: "blocked_in_phase_8b" for field in blocked_fields},
            next_phase_handoff={
                "current_phase": "Phase 8B - Safe Frontend Generator Contract",
                "next_phase": "Phase 8C - Single Page Static Preview Generator",
                "handoff_status": "approval_gated",
                "generation_status": "locked",
            },
            safety_limits=[
                "No real frontend generation.",
                "No HTML output.",
                "No CSS output.",
                "No React output.",
                "No generated files.",
                "No writes to generated-apps.",
                "No provider calls.",
                "No Supabase, authentication, or database writes.",
                "No deployment.",
                "Phase 8 generation remains locked.",
            ],
        )
